Repository http4s/http4s, pull requests merged in 2018-09, with the labels that each got.

#2052 Create an expiring test scheduler
  blaze-client/src/test/scala/org/http4s/client/blaze/ClientTimeoutSpec.scala
  client/src/test/scala/org/http4s/client/JavaNetClientSpec.scala
  testing/src/test/scala/org/http4s/Http4sSpec.scala
Labels: testing

#2069 Renames incorrect, duplicate withIdleTimeout to withMaxTotalConnections
  blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientBuilder.scala
Labels: bug

#2077 Scala Code of Conduct
  CODE_OF_CONDUCT.md
  README.md
  website/src/hugo/content/code-of-conduct.md
  website/src/hugo/content/getting-help.md
Labels: docs

#2106 Don't start response until after we add async timeout listener
  jetty/src/test/scala/org/http4s/server/jetty/JettyServerSpec.scala
  servlet/src/main/scala/org/http4s/servlet/AsyncHttp4sServlet.scala
  servlet/src/main/scala/org/http4s/servlet/BlockingHttp4sServlet.scala
  servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
  servlet/src/main/scala/org/http4s/servlet/ServletIo.scala
  servlet/src/main/scala/org/http4s/servlet/package.scala
  tomcat/src/test/scala/org/http4s/tomcat/TomcatServerSpec.scala
Labels: bug

#2113 Enable unusedCompileDependenciesTest
  build.sbt
  project/Http4sPlugin.scala
  project/PrivateProject.scala
  project/plugins.sbt
Labels: CI

#2115 Stop testing oraclejdk10
  .travis.yml
Labels: CI

#2116 s/oraclejdk10/oraclejdk11/ on 0.18.x
  .travis.yml
Labels: CI

#2079 #2071 use read range of fs2
  core/src/main/scala/org/http4s/StaticFile.scala
Labels: don't merge yet

#2127 Remove MiMa opt-outs for recent modules
  build.sbt
Labels: CI

#2128 Don't check for dependency updates on load
  build.sbt
Labels: CI
