Repository http4s/http4s, pull requests merged in 2018-05, with the labels that each got.

#1820 copy server logging middleware to client module
  client/src/main/scala/org/http4s/client/middleware/Logger.scala
  client/src/main/scala/org/http4s/client/middleware/RequestLogger.scala
  client/src/main/scala/org/http4s/client/middleware/ResponseLogger.scala
  client/src/test/resources/testresource.txt
  client/src/test/scala/org/http4s/client/middleware/LoggerSpec.scala
Labels: enhancement

#1824 Fix broken client logger merge
  client/src/main/scala/org/http4s/client/middleware/Logger.scala
  client/src/main/scala/org/http4s/client/middleware/RequestLogger.scala
  client/src/main/scala/org/http4s/client/middleware/ResponseLogger.scala
  client/src/test/scala/org/http4s/client/middleware/LoggerSpec.scala
Labels: CI, bug

#1838 Fix Http4sServlet compilation on 2.11
  servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
Labels: CI

#1837 Fix deadlock in client logging middleware
  blaze-client/src/test/scala/org/http4s/client/blaze/PooledClientSpec.scala
  client/src/main/scala/org/http4s/client/middleware/Logger.scala
  client/src/main/scala/org/http4s/client/middleware/RequestLogger.scala
  client/src/main/scala/org/http4s/client/middleware/ResponseLogger.scala
  client/src/test/scala/org/http4s/client/middleware/LoggerSpec.scala
Labels: bug

#1836 Remove httpbin.org dependency from client tests
  blaze-client/src/test/resources/server.jks
  blaze-client/src/test/scala/org/http4s/client/blaze/PooledClientSpec.scala
  client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
  client/src/test/scala/org/http4s/client/JettyScaffold.scala
Labels: CI, testing

#1839 Removed fixed log level from Logger
  client/src/main/scala/org/http4s/client/middleware/Logger.scala
  client/src/main/scala/org/http4s/client/middleware/RequestLogger.scala
  client/src/main/scala/org/http4s/client/middleware/ResponseLogger.scala
  server/src/main/scala/org/http4s/server/middleware/Logger.scala
  server/src/main/scala/org/http4s/server/middleware/RequestLogger.scala
  server/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala
Labels: enhancement

#1842 better-monadic-for is better
  project/Http4sPlugin.scala
Labels: enhancement

#1843 Enable -Ybackend-parallelism where appropriate
  project/Http4sPlugin.scala
Labels: CI

#1846 Log whatever part of the response has been read
  client/src/main/scala/org/http4s/client/middleware/ResponseLogger.scala
Labels: bug

#1865 Multipart default improvements, mixed file/in memory streaming decoder
  core/src/main/scala/org/http4s/EntityEncoder.scala
  core/src/main/scala/org/http4s/multipart/MultipartDecoder.scala
  core/src/main/scala/org/http4s/multipart/MultipartParser.scala
  core/src/main/scala/org/http4s/multipart/Part.scala
  tests/src/test/scala/org/http4s/multipart/MultipartParserSpec.scala
  tests/src/test/scala/org/http4s/multipart/MultipartSpec.scala
Labels: enhancement

#1864 Add an OkHttp client (with HTTP/2) (to 0.18)
  build.sbt
  okhttp-client/src/main/scala/org/http4s/client/okhttp/OkHttp.scala
  okhttp-client/src/test/scala/org/http4s/client/okhttp/OkHttpClientSpec.scala
  project/Http4sPlugin.scala
Labels: enhancement

#1869 Extend query paramater docs #1868
  docs/src/main/tut/dsl.md
Labels: docs

#1887 Fix deprecation in dsl tut
  docs/src/main/tut/dsl.md
Labels: docs

#1885 Generalize AutoSlash middleware
  server/src/main/scala/org/http4s/server/middleware/AutoSlash.scala
  website/src/hugo/content/changelog.md
Labels: enhancement

#1886 Parameterize ChunkAggregator
  examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/Module.scala
  server/src/main/scala/org/http4s/server/middleware/ChunkAggregator.scala
  server/src/test/scala/org/http4s/server/middleware/ChunkAggregatorSpec.scala
  website/src/hugo/content/changelog.md
Labels: enhancement

#1889 Generalize CORS middleware
  server/src/main/scala/org/http4s/server/middleware/CORS.scala
  website/src/hugo/content/changelog.md
Labels: enhancement
