Repository http4s/http4s, pull requests merged in 2018-06, with the labels that each got.

#1870 Docs: improve client doc
  client/src/main/scala/org/http4s/client/Client.scala
  docs/src/main/tut/client.md
Labels: docs

#1925 Test on oraclejdk10
  .travis.yml
  website/src/hugo/content/changelog.md
Labels: CI

#1917 Implement optional implicit allowing usage of circe decoders without EntityDecoder definition
  circe/src/main/scala/org/http4s/circe/CirceEntityCodec.scala
  circe/src/main/scala/org/http4s/circe/CirceEntityDecoder.scala
  circe/src/main/scala/org/http4s/circe/CirceEntityEncoder.scala
  circe/src/main/scala/org/http4s/circe/CirceInstances.scala
  circe/src/test/scala/org/http4s/circe/CirceSpec.scala
  docs/src/main/tut/json.md
Labels: enhancement
