Repository http4s/http4s, pull requests merged in 2018-02, with the labels that each got.

#1666 Promote avias and tsec
  website/src/hugo/content/adopters.md
Labels: documentation

#1668 Simplify renderResponse in the ClientRouteTestBattery
  client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
Labels: continuous-integration, testing

#1675 Fix race condition between shutdown and parsing in Http1ServerStage (#1487)
  blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
Labels: bug

#1678 Don't use filter in Arbitrary[`Content-Length`]
  testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala
Labels: testing
