Repository http4s/http4s, pull requests merged in 2018-11, with the labels that each got.

#2231 Fix off-by-one error in maxWaitQueueLimit
  client/src/main/scala/org/http4s/client/PoolManager.scala
  client/src/test/scala/org/http4s/client/PoolManagerSpec.scala
Labels: bug

#2239 Define an allocated that doesn't hang on failure
  client/src/main/scala/org/http4s/client/DefaultClient.scala
  core/src/main/scala/org/http4s/internal/package.scala
  tests/src/test/scala/org/http4s/internal/AllocatedSpec.scala
Labels: bug

#2063 Support cancellation in blaze-server on stage shutdown
  blaze-core/src/test/scala/org/http4s/blazecore/TestHead.scala
  blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
  blaze-server/src/test/scala/org/http4s/server/blaze/Http1ServerStageSpec.scala
Labels: enhancement

#2241 Only add the idle timeout stage when idleTimeout is finite
  blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala
  blaze-core/src/main/scala/org/http4s/blazecore/IdleTimeoutStage.scala
Labels: bug

#1687 Link header
  blaze-server/src/test/scala/org/http4s/server/blaze/Http1ServerStageSpec.scala
  core/src/main/scala/org/http4s/headers/Link.scala
  core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
  core/src/main/scala/org/http4s/parser/LinkHeader.scala
  testing/src/main/scala/org/http4s/testing/ArbitraryInstances.scala
  tests/src/test/scala/org/http4s/headers/LinkSpec.scala
Labels: enhancement

#2260 Fix leak on a canceled connection
  blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClient.scala
  blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientSpec.scala
Labels: bug

#2267 Drop appveyor build
  .appveyor.yml
Labels: CI

#2242 Support channel options on BlazeServerBuilder
  blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientBuilder.scala
  blaze-core/src/main/scala/org/http4s/blazecore/BlazeBackendBuilder.scala
  blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala
  blaze-server/src/test/scala/org/http4s/server/blaze/BlazeServerSpec.scala
Labels: enhancement

#2285 Deprecate BlazeServer companion, forward to BlazeServerBuilder
  blaze-server/src/main/scala/org/http4s/server/blaze/BlazeBuilder.scala
  blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala
  docs/src/main/tut/client.md
  docs/src/main/tut/service.md
  examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeMetricsExample.scala
Labels: bug

#2281 Fix Issue #2280 `org.http4s.util.decode` throws `ClassCastException` on empty chunk
  core/src/main/scala/org/http4s/util/package.scala
  tests/src/test/scala/org/http4s/util/DecodeSpec.scala
Labels: bug
