Repository http4s/http4s, pull requests merged in 2018-03, with the labels that each got.

#1734 Fix the versions table on the site
  scripts/helpers
Labels: documentation

#1735 Tune scalacheck parameters for SemigroupK[EntityDecoder[IO, ?]]
  tests/src/test/scala/org/http4s/EntityDecoderSpec.scala
Labels: testing

#1738 Set up /stable and /latest rewrites
  build.sbt
  website/src/hugo/static/_redirects
Labels: documentation

#1718 Add Testing Docs for v0.18
  docs/src/main/tut/testing.md
Labels: docs

#1752 Fix deprecated call in testing.md
  docs/src/main/tut/testing.md
Labels: docs

#1748 Fix failure in ContentCodingSpec
  tests/src/test/scala/org/http4s/ContentCodingSpec.scala
Labels: testing

#1753 Update tests to take advantage of cats-effect-0.10
  blaze-client/src/test/scala/org/http4s/client/blaze/PooledClientSpec.scala
  client/src/test/scala/org/http4s/client/testroutes/GetRoutes.scala
  server/src/test/scala/org/http4s/server/middleware/TimeoutSpec.scala
Labels: testing

#1754 Use cats.effect.Timer for Retry middleware
  client/src/main/scala/org/http4s/client/middleware/Retry.scala
Labels: enhancement

#1758 & extractor with doctest
  dsl/src/main/scala/org/http4s/dsl/and.scala
  project/Http4sPlugin.scala
  project/plugins.sbt
Labels: enhancement

#1762 Relax context bounds on various EntityEncoders
  core/src/main/scala/org/http4s/EntityEncoder.scala
Labels: enhancement
