Repository http4s/http4s, pull requests merged in 2018-04, with the labels that each got.

#1761 Upgrade to blaze master
  blaze-client/src/main/scala/org/http4s/client/blaze/BlazeHttp1ClientParser.scala
  blaze-client/src/main/scala/org/http4s/client/blaze/Http1Support.scala
  blaze-core/src/main/scala/org/http4s/blazecore/Http1Stage.scala
  blaze-core/src/main/scala/org/http4s/blazecore/util/Http2Writer.scala
  blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala
  blaze-core/src/main/scala/org/http4s/blazecore/websocket/Serializer.scala
  blaze-core/src/main/scala/org/http4s/blazecore/websocket/SerializingStage.scala
  blaze-core/src/test/scala/org/http4s/blazecore/ResponseParser.scala
  blaze-server/src/main/scala/org/http4s/server/blaze/BlazeBuilder.scala
  blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerParser.scala
  blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
  blaze-server/src/main/scala/org/http4s/server/blaze/Http2NodeStage.scala
  blaze-server/src/main/scala/org/http4s/server/blaze/ProtocolSelector.scala
  blaze-server/src/main/scala/org/http4s/server/blaze/WSFrameAggregator.scala
  blaze-server/src/main/scala/org/http4s/server/blaze/WebSocketDecoder.scala
  blaze-server/src/main/scala/org/http4s/server/blaze/WebSocketSupport.scala
  build.sbt
  project/Http4sPlugin.scala
Labels: enhancement

#1765 Update the further reading page
  website/src/hugo/content/further-reading.md
Labels: docs

#1776 Add a stream constructor for async-http-client
  async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala
Labels: enhancement

#1778 Backport Prometheus Server Metrics
  build.sbt
  project/Http4sPlugin.scala
  prometheus-server-metrics/src/main/scala/org/http4s/server/prometheus/PrometheusExportService.scala
  prometheus-server-metrics/src/main/scala/org/http4s/server/prometheus/PrometheusMetrics.scala
Labels: enhancement

#1785 Don't swallow errors in Http1Writer
  blaze-core/src/main/scala/org/http4s/blazecore/util/Http1Writer.scala
Labels: bug

#1786 Drain the response body after an error setting status/headers
  servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
Labels: bug

#1789 blaze-0.12.13, http4s-websocket-0.2.1, specs2-4.0.4
  project/Http4sPlugin.scala
Labels: enhancement

#1804 sbt-1.1.4, cats-effect-0.10.1, specs2-4.1.0
  project/Http4sPlugin.scala
  project/build.properties
  website/src/hugo/content/changelog.md
Labels: enhancement

#1806 Upgrade to async-http-client-2.4.5
  project/Http4sPlugin.scala
  website/src/hugo/content/changelog.md
Labels: enhancement
