Repository http4s/http4s, pull requests merged in 2020-11, with the labels that each got.

#3820 Remove failed request logging in JettyClient
  jetty-client/src/main/scala/org/http4s/client/jetty/ResponseListener.scala
Labels: enhancement

#3859 Add Ability to pass own client in AsyncHttpClient so that it's state can be referenced
  async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala
  async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClientStats.scala
  async-http-client/src/test/scala/org/http4s/client/asynchttpclient/AsyncHttpClientSpec.scala
Labels: enhancement

#3844 Implement a matrix path variable parser
  dsl/src/main/scala/org/http4s/dsl/impl/Path.scala
  dsl/src/test/scala/org/http4s/dsl/PathSpec.scala
Labels: enhancement

#3870 Update deprecated actions in release.yml
  .github/workflows/ci.yml
  .github/workflows/release.yml
  project/Http4sPlugin.scala
Labels: CI

#3864 Cache Rights of the common HttpVersions
  core/src/main/scala/org/http4s/HttpVersion.scala
Labels: enhancement

#3896 Stop pinning scalameta
  project/build.sbt
  project/plugins.sbt
Labels: CI

#3880 Declare more dependencies
  .github/workflows/ci.yml
  build.sbt
  project/Http4sPlugin.scala
Labels: CI

#3916 Build on pull requests to series/*
  .github/workflows/ci.yml
  project/Http4sPlugin.scala
Labels: CI

#3921 Fix rendering of URIs with colons
  core/src/main/scala/org/http4s/Uri.scala
  tests/src/test/scala/org/http4s/UriSpec.scala
Labels: bug

#3909 Add Order Instance For Header and Headers
  core/src/main/scala/org/http4s/Header.scala
  core/src/main/scala/org/http4s/Headers.scala
  tests/src/test/scala/org/http4s/HeaderSpec.scala
  tests/src/test/scala/org/http4s/HeadersSpec.scala
Labels: enhancement, retarget

#3932 Downgrade to munit-cats-effect-0.8.0, curse 0.9.0
  ember-core/src/test/scala/org/http4s/ember/core/TraversalSpec.scala
  project/Http4sPlugin.scala
  website/src/hugo/content/changelog.md
Labels: bug

#3934 Fix docs for client DSL changes in #3903
  docs/src/main/mdoc/client.md
  docs/src/main/mdoc/dsl.md
  docs/src/main/mdoc/json.md
Labels: CI, docs

#3937 Add Order And Hash Instance For Charset
  core/src/main/scala/org/http4s/Charset.scala
  tests/src/test/scala/org/http4s/CharsetSpec.scala
Labels: enhancement
