Repository http4s/http4s, pull requests merged in 2020-10, with the labels that each got.

#3738 resolving PrometheusExportService path comparison failure
  prometheus-metrics/src/main/scala/org/http4s/metrics/prometheus/PrometheusExportService.scala
Labels: bug

#3440 Simplify Method model
  client/src/main/scala/org/http4s/client/Http4sClientDsl.scala
  client/src/main/scala/org/http4s/client/impl/RequestGenerator.scala
  client/src/test/scala/org/http4s/client/middleware/FollowRedirectSpec.scala
  core/src/main/scala/org/http4s/Method.scala
Labels: breaking

#3742 JDK 1.14 -> JDK 1.15
  .github/workflows/ci.yml
Labels: CI

#3735 Gzip in webjar service
  server/src/main/scala/org/http4s/server/staticcontent/WebjarService.scala
  server/src/test/resources/META-INF/resources/webjars/test-lib/1.0.0/testresource.txt.gz
  server/src/test/scala/org/http4s/server/staticcontent/StaticContentShared.scala
  server/src/test/scala/org/http4s/server/staticcontent/WebjarServiceSpec.scala
Labels: enhancement

#3641 added a FormDataDecoder
  core/src/main/scala/org/http4s/FormDataDecoder.scala
  tests/src/test/scala/org/http4s/FormDataDecoderSpec.scala
Labels: enhancement, retarget

#3737 Omnibus dependency upgrade before 0.21.8
  build.sbt
  dropwizard-metrics/src/test/scala/org/http4s/metrics/dropwizard/DropwizardClientMetricsSpec.scala
  dropwizard-metrics/src/test/scala/org/http4s/metrics/dropwizard/DropwizardServerMetricsSpec.scala
  project/Http4sPlugin.scala
  project/build.sbt
  prometheus-metrics/src/test/scala/org/http4s/metrics/prometheus/PrometheusClientMetricsSpec.scala
  prometheus-metrics/src/test/scala/org/http4s/metrics/prometheus/PrometheusServerMetricsSpec.scala
  server/src/test/scala/org/http4s/server/middleware/EntityLimiterSpec.scala
  tests/src/test/scala/org/http4s/HeaderSpec.scala
  tests/src/test/scala/org/http4s/StaticFileSpec.scala
  tests/src/test/scala/org/http4s/headers/AgeSpec.scala
Labels: enhancement

#3366 proposal: improve client errors handling
  client/src/main/scala/org/http4s/client/Client.scala
  client/src/main/scala/org/http4s/client/DefaultClient.scala
  client/src/test/scala/org/http4s/client/ClientSyntaxSpec.scala
  client/src/test/scala/org/http4s/client/UnexpectedStatusSpec.scala
  client/src/test/scala/org/http4s/client/middleware/FollowRedirectSpec.scala
  dropwizard-metrics/src/test/scala/org/http4s/metrics/dropwizard/DropwizardClientMetricsSpec.scala
  prometheus-metrics/src/test/scala/org/http4s/metrics/prometheus/PrometheusClientMetricsSpec.scala
Labels: breaking

#3758 Refactor query param infix operators to avoid 2.13 error
  core/src/main/scala/org/http4s/QueryOps.scala
  tests/src/test/scala/org/http4s/UriSpec.scala
Labels: breaking

#3772 Skip flaky Insert a User-Agent header test
  blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSpec.scala
Labels: CI, testing

#3776 Skip another flaky blaze-client test
  blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientSpec.scala
Labels: CI, testing
