Repository http4s/http4s, pull requests merged in 2020-06, with the labels that each got.

#3325 Implement WebSocket stream with a single send-receive pipe
  blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala
  blaze-core/src/test/scala/org/http4s/blazecore/websocket/Http4sWSStageSpec.scala
  core/src/main/scala/org/http4s/websocket/WebSocket.scala
  examples/blaze/src/main/scala/com/example/http4s/blaze/BlazeWebSocketExample.scala
  server/src/main/scala/org/http4s/server/websocket/WebSocketBuilder.scala
Labels: breaking

#3512 Fix CIString reference in middleware.md
  docs/src/main/mdoc/middleware.md
Labels: docs

#3410 Update docs for BlazeClientBuilder
  blaze-client/src/main/scala/org/http4s/client/blaze/BlazeClientBuilder.scala
Labels: RFC, docs

#3488 Don't call .toString on ResponseLogger input
  server/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala
Labels: bug

#3521 Raise throwables into body if streaming has begun
  async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala
Labels: bug

#3518 Fix Cogen[ContentCoding]
  laws/src/main/scala/org/http4s/laws/discipline/ArbitraryInstances.scala
  tests/src/test/scala/org/http4s/ContentCodingSpec.scala
Labels: bug

#3526 Integrate scalafix as a first-class module
  .github/workflows/ci.yml
  .github/workflows/release.yml
  build.sbt
  project/Http4sPlugin.scala
  project/plugins.sbt
  scalafix/build.sbt
  scalafix/project/build.properties
  scalafix/project/plugins.sbt
  scalafix/rules/src/main/scala/fix/ClientFetchPatches.scala
  scalafix/rules/src/main/scala/fix/package.scala
  scalafix/rules/src/main/scala/fix/v0_21.scala
  scalafix/tests/src/test/scala/fix/RuleSuite.scala
Labels: CI

#3545 Update getting started
  docs/src/main/mdoc/index.md
Labels: docs

#3548 Read directory fix series 21
  core/src/main/scala/org/http4s/StaticFile.scala
  tests/src/test/resources/foo/fooz.txt
  tests/src/test/scala/org/http4s/StaticFileSpec.scala
Labels: bug
