Repository http4s/http4s, pull requests merged in 2020-05, with the labels that each got.

#3393 Remove stale MiMa filters from blaze-core
  build.sbt
Labels: CI

#3398 Remove scalastyle
  core/src/main/scala/org/http4s/Message.scala
  core/src/main/scala/org/http4s/QValue.scala
  core/src/main/scala/org/http4s/Status.scala
  core/src/main/scala/org/http4s/Uri.scala
  core/src/main/scala/org/http4s/multipart/MultipartParser.scala
  core/src/main/scala/org/http4s/package.scala
  core/src/main/scala/org/http4s/parser/AdditionalRules.scala
  core/src/main/scala/org/http4s/parser/AuthorizationHeader.scala
  core/src/main/scala/org/http4s/parser/CookieHeader.scala
  core/src/main/scala/org/http4s/parser/RequestUriParser.scala
  core/src/main/scala/org/http4s/parser/Rfc2616BasicRules.scala
  core/src/main/scala/org/http4s/parser/Rfc3986Parser.scala
  project/plugins.sbt
  scalastyle-config.xml
Labels: CI

#3404 Drop mention of http4s-argonaut61
  docs/src/main/tut/json.md
Labels: docs

#3402 Refer to SBT configs by constants
  build.sbt
Labels: CI

#3405 Remove sbt-coursier plugin
  project/plugins.sbt
Labels: CI

#3401 Don't redundantly set git.remoteRepo
  project/Http4sPlugin.scala
Labels: CI

#3406 Don't remove -Ywarn-unused:imports from doc
  build.sbt
Labels: CI

#3403 Remove ivy logging level config
  build.sbt
Labels: CI

#3391 Remove cancelable := true, now the default
  build.sbt
Labels: CI

#3395 Remove http4sJvmTarget setting
  build.sbt
  project/Http4sPlugin.scala
Labels: CI

#3397 Remove unused compile dep filter on scala-reflect
  project/Http4sPlugin.scala
Labels: CI

#3394 Remove YourKit JSP workaround
  build.sbt
  project/Http4sPlugin.scala
Labels: CI

#3396 Remove unused params workaround on sbt-doctest
  project/Http4sPlugin.scala
Labels: CI

#3392 Remove snapshots resolver from core
  build.sbt
Labels: CI

#3266 Update fs2-io, fs2-reactive-streams to 2.3.0
  client/src/main/scala/org/http4s/client/middleware/GZip.scala
  server/src/main/scala/org/http4s/server/middleware/GZip.scala
Labels: breaking

#3399 Backport #3358: Replace tut with mdoc
  build.sbt
  docs/src/hugo/config.toml
  docs/src/hugo/layouts/partials/edit-button.html
  docs/src/hugo/layouts/partials/edit-link.html
  docs/src/main/mdoc/auth.md
  docs/src/main/mdoc/client.md
  docs/src/main/mdoc/cors.md
  docs/src/main/mdoc/csrf.md
  docs/src/main/mdoc/dsl.md
  docs/src/main/mdoc/entity.md
  docs/src/main/mdoc/error-handling.md
  docs/src/main/mdoc/gzip.md
  docs/src/main/mdoc/hsts.md
  docs/src/main/mdoc/index.md
  docs/src/main/mdoc/json.md
  docs/src/main/mdoc/methods.md
  docs/src/main/mdoc/middleware.md
  docs/src/main/mdoc/service.md
  docs/src/main/mdoc/static.md
  docs/src/main/mdoc/streaming.md
  docs/src/main/mdoc/testing.md
  docs/src/main/mdoc/upgrading.md
  docs/src/main/mdoc/uri.md
  project/plugins.sbt
  website/src/hugo/content/contributing.md
Labels: docs

#3374 Docs/deployment
  docs/src/main/tut/deployment.md
Labels: docs

#3416 Docs non static
  docs/src/main/tut/deployment.md
Labels: docs

#3400 http4s.org SBT plugin
  build.sbt
  project/Http4sPlugin.scala
  project/PrivateProjectPlugin.scala
  project/plugins.sbt
Labels: CI

#3421 Update deployment.md
  docs/src/main/mdoc/deployment.md
Labels: docs

#3309 Update async-http-client to 2.12.1
  async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala
  async-http-client/src/main/scala/org/http4s/client/asynchttpclient/NoOpCookieStore.scala
  project/Http4sPlugin.scala
Labels: breaking

#3438 Add PRI method
  core/src/main/scala/org/http4s/Method.scala
Labels: enhancement

#3221 Change Uri.Path to be own type
  .gitignore
  blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala
  blaze-server/src/test/scala/org/http4s/server/blaze/Http1ServerStageSpec.scala
  blaze-server/src/test/scala/org/http4s/server/blaze/ServerTestRoutes.scala
  circe/src/main/scala/org/http4s/circe/middleware/JsonDebugErrorHandler.scala
  client/src/main/scala/org/http4s/client/middleware/CookieJar.scala
  client/src/test/scala/org/http4s/client/ClientSyntaxSpec.scala
  core/src/main/scala/org/http4s/LiteralSyntaxMacros.scala
  core/src/main/scala/org/http4s/Message.scala
  core/src/main/scala/org/http4s/Uri.scala
  core/src/main/scala/org/http4s/UriTemplate.scala
  core/src/main/scala/org/http4s/metrics/MetricsOps.scala
  core/src/main/scala/org/http4s/parser/RequestUriParser.scala
  core/src/main/scala/org/http4s/parser/Rfc3986Parser.scala
  core/src/main/scala/org/http4s/syntax/LiteralsSyntax.scala
  core/src/main/scala/org/http4s/syntax/StringSyntax.scala
  docs/src/main/mdoc/client.md
  docs/src/main/mdoc/uri.md
  dsl/src/main/scala/org/http4s/dsl/impl/Path.scala
  dsl/src/test/scala/org/http4s/dsl/PathInHttpRoutesSpec.scala
  examples/blaze/src/main/scala/com/example/http4s/blaze/ClientMultipartPostExample.scala
  examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/service/GitHubService.scala
  laws/src/main/scala/org/http4s/laws/discipline/ArbitraryInstances.scala
  server/src/main/scala/org/http4s/server/ContextRouter.scala
  server/src/main/scala/org/http4s/server/Router.scala
  server/src/main/scala/org/http4s/server/Server.scala
  server/src/main/scala/org/http4s/server/middleware/AutoSlash.scala
  server/src/main/scala/org/http4s/server/middleware/PushSupport.scala
  server/src/main/scala/org/http4s/server/middleware/TranslateUri.scala
  server/src/main/scala/org/http4s/server/staticcontent/FileService.scala
  server/src/main/scala/org/http4s/server/staticcontent/ResourceService.scala
  server/src/main/scala/org/http4s/server/staticcontent/WebjarService.scala
  server/src/test/scala/org/http4s/server/ContextRouterSpec.scala
  server/src/test/scala/org/http4s/server/HttpRoutesSpec.scala
  server/src/test/scala/org/http4s/server/MockRoute.scala
  server/src/test/scala/org/http4s/server/RouterSpec.scala
  server/src/test/scala/org/http4s/server/middleware/CORSSpec.scala
  server/src/test/scala/org/http4s/server/middleware/EntityLimiterSpec.scala
  server/src/test/scala/org/http4s/server/middleware/HttpsRedirectSpec.scala
  server/src/test/scala/org/http4s/server/middleware/TranslateUriSpec.scala
  server/src/test/scala/org/http4s/server/middleware/authentication/AuthenticationSpec.scala
  server/src/test/scala/org/http4s/server/staticcontent/WebjarServiceFilterSpec.scala
  server/src/test/scala/org/http4s/server/staticcontent/WebjarServiceSpec.scala
  servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
  tests/src/test/scala/org/http4s/MessageSpec.scala
  tests/src/test/scala/org/http4s/UriSpec.scala
  tests/src/test/scala/org/http4s/UriTemplateSpec.scala
  tests/src/test/scala/org/http4s/multipart/MultipartSpec.scala
  tests/src/test/scala/org/http4s/parser/UriParserSpec.scala
Labels: breaking
