Repository http4s/http4s, pull requests merged in 2020-02, with the labels that each got.

#3139 Change behaviour of Router to use segments
  server/src/main/scala/org/http4s/server/ContextRouter.scala
  server/src/main/scala/org/http4s/server/Router.scala
  server/src/test/scala/org/http4s/server/ContextRouterSpec.scala
  server/src/test/scala/org/http4s/server/RouterSpec.scala
Labels: enhancement

#3124 Change Effect to Sync in FileService
  server/src/main/scala/org/http4s/server/staticcontent/CacheStrategy.scala
  server/src/main/scala/org/http4s/server/staticcontent/FileService.scala
  server/src/main/scala/org/http4s/server/staticcontent/MemoryCache.scala
  server/src/main/scala/org/http4s/server/staticcontent/NoopCacheStrategy.scala
Labels: breaking

#3136 Added new WS API which allows receiving Ping messages from the client
  blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala
  blaze-core/src/test/scala/org/http4s/blazecore/websocket/Http4sWSStageSpec.scala
  server/src/main/scala/org/http4s/server/websocket/WebSocketBuilder.scala
Labels: breaking

#3138 Purged the unnecessary Applicative constraint from EntityEncoder instances
  argonaut/src/main/scala/org/http4s/argonaut/ArgonautInstances.scala
  boopickle/src/main/scala/org/http4s/booPickle/BooPickleInstances.scala
  circe/src/main/scala/org/http4s/circe/CirceEntityEncoder.scala
  dropwizard-metrics/src/main/scala/org/http4s/metrics/dropwizard/metrics.scala
  json4s/src/main/scala/org/http4s/json4s/Json4sInstances.scala
  play-json/src/main/scala/org/http4s/play/PlayEntityEncoder.scala
  play-json/src/main/scala/org/http4s/play/PlayInstances.scala
  scala-xml/src/main/scala/scalaxml/ElemInstances.scala
  scalatags/src/main/scala/org/http4s/scalatags/ScalatagsInstances.scala
Labels: breaking

#3140 Refactor Tomcat SSL config, deprecate abandoned ServerBuilder
  examples/jetty/src/main/scala/com/example/http4s/jetty/JettySslExample.scala
  jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
  server/src/main/scala/org/http4s/server/ServerBuilder.scala
  tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala
Labels: breaking

#3147 Add GitHub Action
  .github/workflows/ci.yml
Labels: CI

#3148 Add HttpRoutes.strict
  core/src/main/scala/org/http4s/ContextRoutes.scala
  core/src/main/scala/org/http4s/HttpRoutes.scala
  tests/src/test/scala/org/http4s/HttpRoutesSpec.scala
Labels: enhancement

#3149 Add CI=true environment variable
  .github/workflows/ci.yml
Labels: CI

#3157 Alternate GET body cleanup test
  server/src/test/scala/org/http4s/server/middleware/DefaultHeadSpec.scala
Labels: CI, testing

#3151 Migrate to sbt-ci-release, remove Travis CI
  .github/workflows/release.yml
  .travis.yml
  build.sbt
  project/.gnupg/secret.tar.enc
  project/Http4sPlugin.scala
  project/PrivateProjectPlugin.scala
  project/plugins.sbt
  project/travis-deploy-key.enc
  scripts/helpers
  testing/src/test/scala/org/http4s/Http4sSpec.scala
  tests/src/test/scala/org/http4s/StaticFileSpec.scala
Labels: CI

#3159 Publish signed snapshots
  .github/workflows/ci.yml
Labels: CI

#3161 Base URL of site assets is determined by $CI
  .github/workflows/release.yml
Labels: CI, docs

#3163 Remove version.sbt
  version.sbt
Labels: CI

#3164 Use setup-scala GitHub Action
  .github/workflows/ci.yml
Labels: CI

#3172 Fix broken ci.yml
  .github/workflows/ci.yml
Labels: CI

#3174 Drop prometheus dependency on http4s-dsl
  build.sbt
  prometheus-metrics/src/main/scala/org/http4s/metrics/prometheus/PrometheusExportService.scala
Labels: breaking

#3175 Backport GitHubActions to 0.20.x
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .travis.yml
  build.sbt
  project/Http4sPlugin.scala
  project/travis-deploy-key.enc
  scripts/helpers
  tests/src/test/scala/org/http4s/StaticFileSpec.scala
Labels: CI

#3176 Fix client auth values in TomcatBuilder
  tomcat/src/main/scala/org/http4s/server/tomcat/TomcatBuilder.scala
Labels: bug

#3180 Further detravissification for 0.20.x
  project/Http4sPlugin.scala
  project/PrivateProjectPlugin.scala
  project/plugins.sbt
Labels: CI

#3181 Mark 0.21 as stable
  website/src/hugo/themes/http4s.org/layouts/partials/nav-docs.html
Labels: docs

#3184 ResponseCookie parsing improvements (0.20.x)
  core/src/main/scala/org/http4s/ResponseCookie.scala
  core/src/main/scala/org/http4s/parser/CookieHeader.scala
  tests/src/test/scala/org/http4s/parser/CookieHeaderSpec.scala
Labels: bug

#3190 Replace runtime reflection in HttpHeaderParser init
  core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
Labels: enhancement

#3195 Fix scalafmt in CI
  .github/workflows/ci.yml
Labels: CI

#3192 Fix case sensitivity of SameSite
  core/src/main/scala/org/http4s/parser/CookieHeader.scala
  tests/src/test/scala/org/http4s/parser/CookieHeaderSpec.scala
Labels: bug

#3206 Model Content-Location header
  core/src/main/scala/org/http4s/headers/Content-Location.scala
  core/src/main/scala/org/http4s/parser/ContentLocationHeader.scala
  core/src/main/scala/org/http4s/parser/HttpHeaderParser.scala
  tests/src/test/scala/org/http4s/parser/ContentLocationHeaderSpec.scala
Labels: enhancement

#3207 Run scalafmt as intended
  .github/workflows/ci.yml
Labels: CI

#3167 Add Helper Function to Build classifierF (to pass to client and server's Middleware)
  core/src/main/scala/org/http4s/metrics/MetricsOps.scala
  tests/src/test/scala/org/http4s/metrics/MetricsOpsSpec.scala
Labels: enhancement
