Repository http4s/http4s, pull requests merged in 2020-08, with the labels that each got.

#3583 Fixes #3034 Allow configuring circe support parser
  circe/src/main/scala/org/http4s/circe/CirceInstances.scala
  circe/src/test/scala/org/http4s/circe/CirceSpec.scala
Labels: breaking

#3595 Update dsl.md
  docs/src/main/mdoc/dsl.md
Labels: docs

#3625 Close urlConn in StaticFile.fromURL
  core/src/main/scala/org/http4s/StaticFile.scala
Labels: bug

#3624 Use defaultHttpClient in JettyClient builder
  jetty-client/src/main/scala/org/http4s/client/jetty/JettyClient.scala
Labels: bug, retarget

#3602 Add Trailer Headers to Ember
  build.sbt
  ember-core/src/main/scala/org/http4s/ember/core/ChunkedEncoding.scala
  ember-core/src/main/scala/org/http4s/ember/core/Parser.scala
  ember-core/src/main/scala/org/http4s/ember/core/Shared.scala
  ember-core/src/test/scala/org/http4s/ember/core/ParsingSpec.scala
  ember-core/src/test/scala/org/http4s/ember/core/TraversalSpec.scala
Labels: enhancement

#3630 Update Scala versions in .mergify.yml
  .mergify.yml
Labels: CI

#3621 Remove Scalafix from mergify config
  .mergify.yml
Labels: CI
