Repository http4s/http4s, pull requests merged in 2020-01, with the labels that each got.

#3109 Remove Http4sSpec.writeToChunk
  testing/src/test/scala/org/http4s/Http4sSpec.scala
Labels: testing

#3108 Move Arbitrary[Chunk[Byte]] out of Http4sSpec
  server/src/test/scala/org/http4s/server/middleware/ChunkAggregatorSpec.scala
  testing/src/test/scala/org/http4s/Http4sSpec.scala
  testing/src/test/scala/org/http4s/testing/fs2Arbitraries.scala
  tests/src/test/scala/org/http4s/EntityCodecSpec.scala
Labels: testing

#3105 Write to blaze websockets with a permit
  blaze-core/src/main/scala/org/http4s/blazecore/websocket/Http4sWSStage.scala
  blaze-core/src/test/scala/org/http4s/blazecore/websocket/Http4sWSStageSpec.scala
  blaze-core/src/test/scala/org/http4s/blazecore/websocket/WSTestHead.scala
Labels: bug

#3106 Interrupt Body of DefaultHead Middleware
  server/src/main/scala/org/http4s/server/middleware/DefaultHead.scala
  server/src/test/scala/org/http4s/server/middleware/DefaultHeadSpec.scala
Labels: enhancement

#3110 MessageFailure: simplify toHttpResponse/inHttpResponse
  circe/src/main/scala/org/http4s/circe/middleware/JsonDebugErrorHandler.scala
  core/src/main/scala/org/http4s/Message.scala
  core/src/main/scala/org/http4s/MessageFailure.scala
  server/src/main/scala/org/http4s/server/middleware/ErrorHandling.scala
  server/src/main/scala/org/http4s/server/middleware/UrlFormLifter.scala
  server/src/main/scala/org/http4s/server/package.scala
  tests/src/test/scala/org/http4s/EntityDecoderSpec.scala
Labels: breaking

#3101 Tests for Request query param convenience methods
  tests/src/test/scala/org/http4s/UriSpec.scala
Labels: testing

#3107 Covary `F` in Message types.
  core/src/main/scala/org/http4s/Media.scala
  core/src/main/scala/org/http4s/Message.scala
  core/src/main/scala/org/http4s/multipart/Part.scala
  tests/src/test/scala/org/http4s/MessageSpec.scala
  tests/src/test/scala/org/http4s/multipart/MultipartSpec.scala
Labels: breaking

#3113 Http4s 3095 Pretty-print an org.http4s.Request as a curl command
  core/src/main/scala/org/http4s/Message.scala
  tests/src/test/scala/org/http4s/MessageSpec.scala
Labels: enhancement

#3115 Fix flaky decode
  core/src/main/scala/org/http4s/util/package.scala
  tests/src/test/scala/org/http4s/util/DecodeSpec.scala
Labels: bug

#3126 Remove Applicative constraint from CirceInstances
  circe/src/main/scala/org/http4s/circe/CirceInstances.scala
  circe/src/main/scala/org/http4s/circe/middleware/JsonDebugErrorHandler.scala
  circe/src/test/scala/org/http4s/circe/CirceSpec.scala
Labels: breaking

#3134 Support SSLParameters in jetty-server
  jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
Labels: enhancement
