Repository http4s/http4s, pull requests merged in 2020-04, with the labels that each got.

#3300 Skip some flaky tests
  blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientSpec.scala
  client/src/test/scala/org/http4s/client/PoolManagerSpec.scala
Labels: CI, testing

#3301 Update mergify rules for Scala 2.12.11
  .mergify.yml
Labels: CI

#3271 Propose API changes
  client/src/main/scala/org/http4s/client/middleware/Metrics.scala
  core/src/main/scala/org/http4s/metrics/MetricsOps.scala
  dropwizard-metrics/src/main/scala/org/http4s/metrics/dropwizard/Dropwizard.scala
  prometheus-metrics/src/main/scala/org/http4s/metrics/prometheus/Prometheus.scala
  prometheus-metrics/src/test/scala/org/http4s/metrics/prometheus/PrometheusClientMetricsSpec.scala
  prometheus-metrics/src/test/scala/org/http4s/metrics/prometheus/PrometheusServerMetricsSpec.scala
  prometheus-metrics/src/test/scala/org/http4s/metrics/prometheus/util.scala
  server/src/main/scala/org/http4s/server/middleware/Metrics.scala
Labels: breaking

#3339 Skip call a second host test on CI
  blaze-client/src/test/scala/org/http4s/client/blaze/BlazeClientSpec.scala
Labels: CI, testing

#3340 Extract dependency versions into own object
  project/Http4sPlugin.scala
Labels: CI

#3341 Extract dependency versions for 0.21
  build.sbt
  project/Http4sPlugin.scala
Labels: CI

#3344 More dependency cleanups
  project/Http4sPlugin.scala
Labels: CI

#3342 Update version dropdowns on site
  website/src/hugo/themes/http4s.org/layouts/partials/nav-docs.html
Labels: docs

#3297 Start testing on JDK-1.14
  .github/workflows/ci.yml
Labels: CI

#3335 Remove unused Client.translate Bracket
  client/src/main/scala/org/http4s/client/Client.scala
Labels: breaking

#3343 Start publishing snapshots for v1.0
  version.sbt
  website/src/hugo/content/versions.md
Labels: CI

#3338 Avoid incorrectly responding with an empty body in AHC client
  async-http-client/src/main/scala/org/http4s/client/asynchttpclient/AsyncHttpClient.scala
Labels: bug

#3350 Use stable hostaddress in ConnectionFailure message
  client/src/main/scala/org/http4s/client/ConnectionFailure.scala
Labels: testing

#3298 Fix JSON detection in client and server Logger
  client/src/main/scala/org/http4s/client/middleware/Logger.scala
  server/src/main/scala/org/http4s/server/middleware/Logger.scala
Labels: enhancement

#3296 Backports to 0.20
  blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
  core/src/main/scala/org/http4s/HttpRoutes.scala
  core/src/main/scala/org/http4s/LiteralSyntaxMacros.scala
  core/src/main/scala/org/http4s/MediaType.scala
  core/src/main/scala/org/http4s/QValue.scala
  core/src/main/scala/org/http4s/util/package.scala
  server/src/main/scala/org/http4s/server/middleware/Caching.scala
  tests/src/test/scala/org/http4s/HttpRoutesSpec.scala
  tests/src/test/scala/org/http4s/util/DecodeSpec.scala
Labels: enhancement

#3295 Release v0.20.22, mark 0.20.x EOL
  website/src/hugo/content/changelog.md
  website/src/hugo/content/versions.md
  website/src/hugo/themes/http4s.org/layouts/partials/nav-docs.html
Labels: docs

#3363 Check MiMa on jetty-client
  build.sbt
Labels: CI

#3347 Use CollectionCompat in WebjarService
  server/src/main/scala/org/http4s/server/staticcontent/WebjarService.scala
Labels: enhancement
