Repository http4s/http4s, pull requests merged in 2020-12, with the labels that each got.

#4006 Set content header on OKHttpClient [targeting series/0.21]
  okhttp-client/src/main/scala/org/http4s/client/okhttp/OkHttpBuilder.scala
Labels: bug

#3913 Regenerate the MimeDB
  core/src/main/scala/org/http4s/MimeDB.scala
Labels: breaking

#4014 Tolerate space in cookie values
  core/src/main/scala/org/http4s/parser/CookieHeader.scala
  tests/src/test/scala/org/http4s/parser/CookieHeaderSpec.scala
Labels: enhancement

#4032 Allow For Providing HttpConfiguration With Jetty
  jetty/src/main/scala/org/http4s/server/jetty/JettyBuilder.scala
  project/ScaladocApiMapping.scala
Labels: enhancement

#4026 Add `Resource` Based Middlewares To `BracketRequestResponse`.
  server/src/main/scala/org/http4s/server/middleware/BracketRequestResponse.scala
Labels: enhancement

#4110 Provide an SslContextFactory to jetty-client
  jetty-client/src/main/scala/org/http4s/client/jetty/JettyClient.scala
Labels: enhancement
