Repository http4s/http4s, pull requests merged in 2021-12, with the labels that each got.

#5648 Publish http4s-scalatags for Scala 3
  build.sbt
Labels: CI, module:scalatags

#5642 EPUB download of the docs for the `series/0.23`
  build.sbt
  project/SiteConfig.scala
Labels: docs, retarget

#5643 Fix the package in the AHC scalafix
  scalafix/input/src/main/scala/fix/RewritePackagesTests.scala
  scalafix/output/src/main/scala/fix/RewritePackagesTests.scala
  scalafix/rules/src/main/scala/fix/v0_22.scala
Labels: bug, scalafix

#5647 Pin scalatags to 0.10
  .scala-steward.conf
Labels: CI, module:scalatags

#5640 EPUB download of the docs
  build.sbt
  project/SiteConfig.scala
Labels: docs

#5676 Add favicon to the `0.22` website and docs
  docs/src/main/mdoc/images/http4s-favicon.png
  docs/src/main/mdoc/images/http4s-favicon.svg
  project/SiteConfig.scala
  website/src/hugo/static/images/http4s-favicon.png
  website/src/hugo/static/images/http4s-favicon.svg
Labels: docs

#5687 Update tomcat-catalina, tomcat-coyote, ... to 9.0.56 in series/0.22
  project/Http4sPlugin.scala
Labels: module:tomcat

#5696 Update discipline to 1.4.0
  .scala-steward.conf
  project/Http4sPlugin.scala
Labels: module:core, series/0.22

#5690 Configure mergify & release notes
  .github/release.yml
  .mergify.yml
Labels: series/0.22

#5698 Update metrics-core, metrics-json to 4.2.5 in series/0.22
  project/Http4sPlugin.scala
Labels: module:dropwizard-metrics, series/0.22

#5601 Netty based ServerScaffold (0.22)
  blaze-client/src/test/scala-2.13/org/http4s/client/blaze/BlazeClient213Suite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientBase.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientSuite.scala
  build.sbt
  client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
  client/src/test/scala/org/http4s/client/JettyScaffold.scala
  client/src/test/scala/org/http4s/client/scaffold/HandlersToNettyAdapter.scala
  client/src/test/scala/org/http4s/client/scaffold/NettyTestServer.scala
  client/src/test/scala/org/http4s/client/scaffold/RoutesToNettyAdapter.scala
  client/src/test/scala/org/http4s/client/scaffold/ServerScaffold.scala
  client/src/test/scala/org/http4s/client/scaffold/package.scala
Labels: testing, module:client, series/0.22

#5587 Netty based ServerScaffold (0.23)
  blaze-client/src/test/scala-2.13/org/http4s/client/blaze/BlazeClient213Suite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientBase.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientSuite.scala
  build.sbt
  client/js/src/test/scala/org/http4s/client/scaffold/ServerScaffold.scala
  client/jvm/src/test/resources/server.jks
  client/jvm/src/test/scala/org/http4s/client/ServerScaffold.scala
  client/jvm/src/test/scala/org/http4s/client/scaffold/HandlersToNettyAdapter.scala
  client/jvm/src/test/scala/org/http4s/client/scaffold/NettyTestServer.scala
  client/jvm/src/test/scala/org/http4s/client/scaffold/RoutesToNettyAdapter.scala
  client/jvm/src/test/scala/org/http4s/client/scaffold/ServerScaffold.scala
  client/jvm/src/test/scala/org/http4s/client/scaffold/package.scala
  client/shared/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
Labels: testing, module:client, series/0.23

#5701 Merge 0.22 to 0.23
  .github/release.yml
  .mergify.yml
  .scala-steward.conf
  project/Http4sPlugin.scala
  project/build.sbt
  website/src/hugo/content/changelog.md
Labels: series/0.23

#5614 Add `Trailer` header
  core/src/main/scala/org/http4s/Headers.scala
  core/src/main/scala/org/http4s/headers/Trailer.scala
  laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
  tests/src/test/scala/org/http4s/headers/TrailerSuite.scala
Labels: series/0.22

#5705 Update netty-buffer, netty-codec-http to 4.1.71.Final in series/0.22
  project/Http4sPlugin.scala
Labels: module:async-http-client, dependencies, series/0.22

#5710 Update sbt to 1.5.6
  project/build.properties
Labels: dependencies

#5713 Update sbt to 1.5.6 in series/0.22
  project/build.properties
Labels: dependencies, series/0.22

#5718 Merge branch `series/0.22` into `series/0.23`
  core/shared/src/main/scala/org/http4s/Headers.scala
  core/shared/src/main/scala/org/http4s/headers/Trailer.scala
  laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
  project/Http4sPlugin.scala
  project/build.properties
  tests/shared/src/test/scala/org/http4s/headers/TrailerSuite.scala
Labels: retarget, series/0.23

#5719 Merge `series/0.23` into `main`
  core/shared/src/main/scala/org/http4s/Headers.scala
  core/shared/src/main/scala/org/http4s/headers/Trailer.scala
  laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
  project/Http4sPlugin.scala
  tests/shared/src/test/scala/org/http4s/headers/TrailerSuite.scala
Labels: retarget

#5319 Introduce blaze-client connection reuse tests
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientBase.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientConnectionReuseSuite.scala
  client/src/test/scala/org/http4s/client/scaffold/NettyTestServer.scala
  client/src/test/scala/org/http4s/client/testroutes/GetRoutes.scala
Labels: module:blaze-client, series/0.22

#5728 Mark the failing tests as flaky because they sometimes pass
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientConnectionReuseSuite.scala
Labels: series/0.22

#5726 Update laika-sbt to 0.18.1 in series/0.22
  project/plugins.sbt
Labels: dependencies, series/0.22

#5729 Remove some outdated params in scaladocs
  blaze-core/src/main/scala/org/http4s/blazecore/util/BodylessWriter.scala
  blaze-server/src/main/scala/org/http4s/blaze/server/BlazeServerBuilder.scala
  core/shared/src/main/scala/org/http4s/internal/ChunkWriter.scala
  prometheus-metrics/src/main/scala/org/http4s/metrics/prometheus/Prometheus.scala
  server/shared/src/main/scala/org/http4s/server/middleware/Timeout.scala
  server/shared/src/main/scala/org/http4s/server/staticcontent/FileService.scala
  server/shared/src/main/scala/org/http4s/server/staticcontent/ResourceService.scala
  server/shared/src/main/scala/org/http4s/server/staticcontent/WebjarService.scala
Labels: docs, series/0.23

#5730 Merge `series/0.22` into `series/0.23`
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientBase.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientConnectionReuseSuite.scala
  client/jvm/src/test/scala/org/http4s/client/scaffold/NettyTestServer.scala
  client/shared/src/test/scala/org/http4s/client/testroutes/GetRoutes.scala
  project/plugins.sbt
Labels: retarget, series/0.23

#5723 Speed up shutdown of NioEventLoopGroups
  client/src/test/scala/org/http4s/client/scaffold/NettyTestServer.scala
Labels: testing, series/0.22

#5734 Merge `series/0.23` into `main`
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientBase.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientConnectionReuseSuite.scala
  blaze-core/src/main/scala/org/http4s/blazecore/util/BodylessWriter.scala
  blaze-server/src/main/scala/org/http4s/blaze/server/BlazeServerBuilder.scala
  client/jvm/src/test/scala/org/http4s/client/scaffold/NettyTestServer.scala
  client/shared/src/test/scala/org/http4s/client/testroutes/GetRoutes.scala
  core/shared/src/main/scala/org/http4s/internal/ChunkWriter.scala
  project/plugins.sbt
  prometheus-metrics/src/main/scala/org/http4s/metrics/prometheus/Prometheus.scala
  server/shared/src/main/scala/org/http4s/server/middleware/Timeout.scala
  server/shared/src/main/scala/org/http4s/server/staticcontent/FileService.scala
  server/shared/src/main/scala/org/http4s/server/staticcontent/ResourceService.scala
  server/shared/src/main/scala/org/http4s/server/staticcontent/WebjarService.scala
Labels: retarget

#5732 Update netty-buffer, netty-codec-http to 4.1.72.Final in series/0.22
  project/Http4sPlugin.scala
Labels: module:async-http-client, dependencies, series/0.22

#5716 Update sbt-scalajs, scalajs-compiler, ... to 1.8.0 in series/0.23
  project/plugins.sbt
Labels: dependencies, series/0.23

#5738 Update logback-classic to 1.2.8 in series/0.22
  project/plugins.sbt
Labels: dependencies, series/0.22

#5735 Mark one more connection reuse test as flaky
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientConnectionReuseSuite.scala
Labels: testing, series/0.22

#5741 `Http1ClientStageSuite` purity
  blaze-client/src/test/scala/org/http4s/blaze/client/Http1ClientStageSuite.scala
Labels: testing, series/0.22

#5747 Update sbt to 1.5.7 in series/0.22
  project/build.properties
Labels: dependencies, series/0.22

#5751 Update logback-classic to 1.2.9 in series/0.22
  project/plugins.sbt
Labels: dependencies, series/0.22

#5753 Merge `series/0.22` into `series/0.23`
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientConnectionReuseSuite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/Http1ClientStageSuite.scala
  client/jvm/src/test/scala/org/http4s/client/scaffold/NettyTestServer.scala
  project/Http4sPlugin.scala
  project/build.properties
  project/plugins.sbt
Labels: retarget, series/0.23

#5755 Code cleanup (mostly variance-related)
  blaze-client/src/test/scala/org/http4s/blaze/client/PoolManagerSuite.scala
  blaze-core/src/main/scala/org/http4s/blazecore/Http1Stage.scala
  blaze-core/src/test/scala/org/http4s/blazecore/util/Http1WriterSpec.scala
  blaze-core/src/test/scala/org/http4s/blazecore/websocket/Http4sWSStageSpec.scala
  blaze-server/src/main/scala/org/http4s/blaze/server/Http2NodeStage.scala
  client/shared/src/main/scala/org/http4s/client/middleware/RequestLogger.scala
  client/shared/src/main/scala/org/http4s/client/middleware/ResponseLogger.scala
  client/shared/src/test/scala/org/http4s/client/middleware/LoggerSuite.scala
  core/shared/src/main/scala/org/http4s/EntityEncoder.scala
  core/shared/src/main/scala/org/http4s/Message.scala
  core/shared/src/main/scala/org/http4s/StaticFile.scala
  core/shared/src/main/scala/org/http4s/multipart/MultipartEncoder.scala
  ember-core/src/main/scala/org/http4s/ember/core/Util.scala
  ember-core/src/test/scala/org/http4s/ember/core/ParserSuite.scala
  ember-server/shared/src/main/scala/org/http4s/ember/server/internal/WebSocketHelpers.scala
  ember-server/shared/src/test/scala/org/http4s/ember/server/EmberServerSuite.scala
  examples/blaze/src/main/scala/com/example/http4s/blaze/demo/StreamUtils.scala
  examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/service/FileService.scala
  examples/ember/src/main/scala/com/example/http4s/ember/EmberServerSimpleExample.scala
  laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
  server/shared/src/main/scala/org/http4s/server/middleware/RequestLogger.scala
  server/shared/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala
  server/shared/src/main/scala/org/http4s/server/staticcontent/MemoryCache.scala
  specs2/src/test/scala/org/http4s/Http4sSpec.scala
  testing/shared/src/test/scala/org/http4s/Http4sSuite.scala
  tests/shared/src/test/scala/org/http4s/ServerSentEventSpec.scala
  tests/shared/src/test/scala/org/http4s/multipart/MultipartParserSuite.scala
  tests/shared/src/test/scala/org/http4s/multipart/MultipartSuite.scala
Labels: series/0.23

#5757 Remove jvm log4cats dependency in ember client js
  build.sbt
  project/Http4sPlugin.scala
  project/plugins.sbt
Labels: series/0.23

#5759 Merge `series/0.23` into `main`
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientConnectionReuseSuite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/Http1ClientStageSuite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/PoolManagerSuite.scala
  blaze-core/src/main/scala/org/http4s/blazecore/Http1Stage.scala
  blaze-core/src/test/scala/org/http4s/blazecore/util/Http1WriterSpec.scala
  blaze-core/src/test/scala/org/http4s/blazecore/websocket/Http4sWSStageSpec.scala
  blaze-server/src/main/scala/org/http4s/blaze/server/Http2NodeStage.scala
  build.sbt
  client/jvm/src/test/scala/org/http4s/client/scaffold/NettyTestServer.scala
  client/shared/src/main/scala/org/http4s/client/middleware/RequestLogger.scala
  client/shared/src/main/scala/org/http4s/client/middleware/ResponseLogger.scala
  client/shared/src/test/scala/org/http4s/client/middleware/LoggerSuite.scala
  core/shared/src/main/scala/org/http4s/Message.scala
  core/shared/src/main/scala/org/http4s/StaticFile.scala
  core/shared/src/main/scala/org/http4s/multipart/MultipartEncoder.scala
  ember-core/src/main/scala/org/http4s/ember/core/Util.scala
  ember-core/src/test/scala/org/http4s/ember/core/ParserSuite.scala
  ember-server/shared/src/main/scala/org/http4s/ember/server/internal/WebSocketHelpers.scala
  ember-server/shared/src/test/scala/org/http4s/ember/server/EmberServerSuite.scala
  examples/blaze/src/main/scala/com/example/http4s/blaze/demo/StreamUtils.scala
  examples/blaze/src/main/scala/com/example/http4s/blaze/demo/server/service/FileService.scala
  examples/ember/src/main/scala/com/example/http4s/ember/EmberServerSimpleExample.scala
  laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
  project/Http4sPlugin.scala
  project/build.properties
  project/plugins.sbt
  server/shared/src/main/scala/org/http4s/server/middleware/RequestLogger.scala
  server/shared/src/main/scala/org/http4s/server/middleware/ResponseLogger.scala
  server/shared/src/main/scala/org/http4s/server/staticcontent/MemoryCache.scala
  specs2/src/test/scala/org/http4s/Http4sSpec.scala
  testing/shared/src/test/scala/org/http4s/Http4sSuite.scala
  tests/shared/src/test/scala/org/http4s/ServerSentEventSpec.scala
  tests/shared/src/test/scala/org/http4s/multipart/MultipartParserSuite.scala
  tests/shared/src/test/scala/org/http4s/multipart/MultipartSuite.scala
Labels: retarget

#5765 Fix scaladoc references to `io.chrisdavenport.vault` in the `series/0.22`
  core/src/main/scala/org/http4s/Message.scala
Labels: docs, series/0.22

#5766 Fix some scaladoc references to headers
  core/src/main/scala/org/http4s/EntityEncoder.scala
  core/src/main/scala/org/http4s/Message.scala
Labels: docs, series/0.22

#5768 Update sbt to 1.5.8 in series/0.22
  project/build.properties
Labels: dependencies, series/0.22

#5770 Update cats-effect, cats-effect-laws, ... to 3.3.1 in series/0.23
  project/Http4sPlugin.scala
Labels: dependencies, series/0.23

#5763 Update metrics-core, metrics-json to 4.2.7 in series/0.22
  project/Http4sPlugin.scala
Labels: dependencies, series/0.22

#5767 Collection micro-opts
  blaze-core/src/main/scala/org/http4s/blazecore/util/CachingChunkWriter.scala
  blaze-core/src/main/scala/org/http4s/blazecore/util/CachingStaticWriter.scala
  blaze-core/src/test/scala/org/http4s/blazecore/util/DumpingWriter.scala
  client/src/test/scala/org/http4s/client/ClientRouteTestBattery.scala
  core/src/main/scala/org/http4s/ResponseCookie.scala
  core/src/main/scala/org/http4s/UriTemplate.scala
  core/src/main/scala/org/http4s/internal/parsing/Rfc3986.scala
  core/src/main/scala/org/http4s/multipart/Boundary.scala
  core/src/main/scala/org/http4s/websocket/FrameTranscoder.scala
  dsl/src/main/scala/org/http4s/dsl/impl/ResponseGenerator.scala
  project/Http4sPlugin.scala
  project/MimeLoader.scala
  server/src/test/scala/org/http4s/server/middleware/HeaderEchoSuite.scala
  server/src/test/scala/org/http4s/server/middleware/ThrottleSuite.scala
  testing/src/test/scala/org/http4s/Http4sSuite.scala
  tests/src/test/scala/org/http4s/HeadersSpec.scala
  tests/src/test/scala/org/http4s/headers/ZipkinHeaderSuite.scala
  tests/src/test/scala/org/http4s/websocket/WebSocketHandshakeSuite.scala
Labels: enhancement, series/0.22

#5777 Rm `sbt-updates` plugin
  project/Http4sPlugin.scala
  project/plugins.sbt
Labels: dependencies, series/0.22

#5778 Merge branch `series/0.22` into `series/0.23`
  blaze-core/src/main/scala/org/http4s/blazecore/util/CachingChunkWriter.scala
  blaze-core/src/main/scala/org/http4s/blazecore/util/CachingStaticWriter.scala
  blaze-core/src/test/scala/org/http4s/blazecore/util/DumpingWriter.scala
  client/shared/src/main/scala/org/http4s/client/Http4sClientDsl.scala
  core/shared/src/main/scala/org/http4s/EntityEncoder.scala
  core/shared/src/main/scala/org/http4s/Message.scala
  core/shared/src/main/scala/org/http4s/ResponseCookie.scala
  core/shared/src/main/scala/org/http4s/UriTemplate.scala
  core/shared/src/main/scala/org/http4s/internal/parsing/Rfc3986.scala
  core/shared/src/main/scala/org/http4s/multipart/Boundary.scala
  core/shared/src/main/scala/org/http4s/websocket/FrameTranscoder.scala
  dsl/src/main/scala/org/http4s/dsl/impl/ResponseGenerator.scala
  project/Http4sPlugin.scala
  project/MimeLoader.scala
  project/build.properties
  project/plugins.sbt
  server/shared/src/test/scala/org/http4s/server/middleware/HeaderEchoSuite.scala
  testing/jvm/src/test/scala/org/http4s/Http4sSuitePlatform.scala
  tests/shared/src/test/scala/org/http4s/HeadersSpec.scala
  tests/shared/src/test/scala/org/http4s/headers/ZipkinHeaderSuite.scala
  tests/shared/src/test/scala/org/http4s/websocket/WebSocketHandshakeSuite.scala
Labels: retarget, series/0.23

#5779 Merge branch `series/0.23` into `main`
  blaze-core/src/main/scala/org/http4s/blazecore/util/CachingChunkWriter.scala
  blaze-core/src/main/scala/org/http4s/blazecore/util/CachingStaticWriter.scala
  blaze-core/src/test/scala/org/http4s/blazecore/util/DumpingWriter.scala
  client/shared/src/main/scala/org/http4s/client/Http4sClientDsl.scala
  core/shared/src/main/scala/org/http4s/EntityEncoder.scala
  core/shared/src/main/scala/org/http4s/Message.scala
  core/shared/src/main/scala/org/http4s/ResponseCookie.scala
  core/shared/src/main/scala/org/http4s/UriTemplate.scala
  core/shared/src/main/scala/org/http4s/internal/parsing/Rfc3986.scala
  core/shared/src/main/scala/org/http4s/multipart/Boundary.scala
  core/shared/src/main/scala/org/http4s/websocket/FrameTranscoder.scala
  dsl/src/main/scala/org/http4s/dsl/impl/ResponseGenerator.scala
  project/Http4sPlugin.scala
  project/MimeLoader.scala
  project/build.properties
  project/plugins.sbt
  server/shared/src/test/scala/org/http4s/server/middleware/HeaderEchoSuite.scala
  testing/jvm/src/test/scala/org/http4s/Http4sSuitePlatform.scala
  tests/shared/src/test/scala/org/http4s/HeadersSpec.scala
  tests/shared/src/test/scala/org/http4s/headers/ZipkinHeaderSuite.scala
  tests/shared/src/test/scala/org/http4s/websocket/WebSocketHandshakeSuite.scala
Labels: retarget

#5761 Improve ClientTimeoutSuite
  blaze-client/src/test/scala/org/http4s/blaze/client/ClientTimeoutSuite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/MockClientBuilder.scala
Labels: testing, series/0.22

#5781 Update logback-classic to 1.2.10 in series/0.22
  project/plugins.sbt
Labels: dependencies, series/0.22

#5788 Update fs2-core, fs2-io, ... to 3.2.4 in series/0.23
  project/Http4sPlugin.scala
Labels: dependencies, series/0.23

#5790 Update sbt to 1.6.0 in series/0.22
  project/build.properties
Labels: dependencies, series/0.22

#5796 Update sbt to 1.6.1 in series/0.22
  project/build.properties
Labels: dependencies, series/0.22

#5801 Update cats-effect, cats-effect-laws, ... to 3.3.2 in series/0.23
  project/Http4sPlugin.scala
Labels: dependencies, series/0.23
