Repository http4s/http4s, pull requests merged in 2021-01, with the labels that each got.

#4143 blaze-client WritePendingException fix
  blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala
  blaze-client/src/test/scala/org/http4s/client/blaze/Http1ClientStageSuite.scala
Labels: bug

#4163 Set the base version to 0.22
  build.sbt
Labels: CI

#4214 Render request URIs in origin form
  blaze-client/src/main/scala/org/http4s/client/blaze/Http1Connection.scala
  core/src/main/scala/org/http4s/Uri.scala
  ember-core/src/main/scala/org/http4s/ember/core/Encoder.scala
  ember-core/src/test/scala/org/http4s/ember/core/EncoderSuite.scala
  tests/src/test/scala/org/http4s/UriSuite.scala
Labels: bug

#4236 Roadmap updates
  website/src/hugo/content/versions.md
  website/src/hugo/themes/http4s.org/layouts/partials/nav-docs.html
Labels: docs

#4238 Shift specs to internal CharPredicate
  tests/src/test/scala/org/http4s/SchemeSpec.scala
  tests/src/test/scala/org/http4s/UriSpec.scala
Labels: testing

#4273 Update Prometheus Client To 0.10.0 And Fix Tests
  project/Http4sPlugin.scala
  prometheus-metrics/src/test/scala/org/http4s/metrics/prometheus/util.scala
Labels: breaking

#4315 Port scala-xml spec to MUnit
  scala-xml/src/test/scala/scalaxml/ScalaXmlSpec.scala
  scala-xml/src/test/scala/scalaxml/ScalaXmlSuite.scala
Labels: testing

#4316 Decouple specs2
  build.sbt
  client/src/test/scala/org/http4s/client/oauth1/OAuthSuite.scala
  scala-xml/src/test/scala/scalaxml/ScalaXmlSpec.scala
  scala-xml/src/test/scala/scalaxml/ScalaXmlSuite.scala
  specs2/src/test/scala/org/http4s/Http4sSpec.scala
  testing/src/test/scala/org/http4s/Http4sSuite.scala
Labels: testing
