Repository http4s/http4s, pull requests merged in 2021-02, with the labels that each got.

#4242 Adopt ip4s
  NOTICE
  blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala
  build.sbt
  circe/src/main/scala/org/http4s/circe/middleware/JsonDebugErrorHandler.scala
  core/src/main/scala/org/http4s/Message.scala
  core/src/main/scala/org/http4s/Uri.scala
  core/src/main/scala/org/http4s/headers/Forwarded.scala
  core/src/main/scala/org/http4s/headers/ForwardedRenderers.scala
  core/src/main/scala/org/http4s/headers/X-Forwarded-For.scala
  core/src/main/scala/org/http4s/internal/parsing/Rfc3986.scala
  examples/src/main/scala/com/example/http4s/ExampleService.scala
  laws/src/main/scala/org/http4s/laws/discipline/ArbitraryInstances.scala
  project/Http4sPlugin.scala
  server/src/test/scala/org/http4s/server/middleware/ErrorActionSuite.scala
  servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
  tests/src/test/scala/org/http4s/Ipv4AddressSpec.scala
  tests/src/test/scala/org/http4s/Ipv6AddressSpec.scala
  tests/src/test/scala/org/http4s/MessageSuite.scala
  tests/src/test/scala/org/http4s/headers/ForwardedArbitraryInstances.scala
  tests/src/test/scala/org/http4s/headers/ForwardedRenderersSpec.scala
  tests/src/test/scala/org/http4s/parser/ForwardedHeaderSpec.scala
  tests/src/test/scala/org/http4s/parser/Rfc3986ParserSpec.scala
  tests/src/test/scala/org/http4s/parser/SimpleHeadersSpec.scala
Labels: breaking

#4370 Deprecate http4s-json4s
  json4s-jackson/src/test/scala/org/http4s/json4s/jackson/Json4sJacksonSuite.scala
  json4s-native/src/test/scala/org/http4s/json4s/native/Json4sNativeSuite.scala
  json4s/src/main/scala/org/http4s/json4s/Json4sInstances.scala
  json4s/src/test/scala/org/http4s/json4s/Json4sSuite.scala
Labels: help wanted

#4403 Remove `Content-Length` and `Content-Encoding` when decompressing
  client/src/main/scala/org/http4s/client/middleware/GZip.scala
  client/src/test/scala/org/http4s/client/middleware/GZipSuite.scala
Labels: bug

#4409 Drop http4s-argonaut
  argonaut/src/main/scala/org/http4s/argonaut/ArgonautInstances.scala
  argonaut/src/main/scala/org/http4s/argonaut/Parser.scala
  argonaut/src/main/scala/org/http4s/argonaut/package.scala
  argonaut/src/test/scala/org/http4s/argonaut/ArgonautSuite.scala
  build.sbt
  docs/src/main/mdoc/entity.md
  docs/src/main/mdoc/json.md
  project/Http4sPlugin.scala
Labels: breaking

#4410 Drop http4s-json4s
  build.sbt
  docs/src/main/mdoc/entity.md
  docs/src/main/mdoc/json.md
  examples/blaze/src/main/scala/com/example/http4s/blaze/ClientExample.scala
  json4s-jackson/src/main/scala/org/http4s/json4s/jackson/Json4sJacksonInstances.scala
  json4s-jackson/src/main/scala/org/http4s/json4s/jackson/package.scala
  json4s-jackson/src/test/scala/org/http4s/json4s/jackson/Json4sJacksonSuite.scala
  json4s-native/src/main/scala/org/http4s/json4s/native/Json4sNativeInstances.scala
  json4s-native/src/main/scala/org/http4s/json4s/native/package.scala
  json4s-native/src/test/scala/org/http4s/json4s/native/Json4sNativeSuite.scala
  json4s/src/main/scala/org/http4s/json4s/Json4sInstances.scala
  json4s/src/test/scala/org/http4s/json4s/Json4sSuite.scala
  project/Http4sPlugin.scala
Labels: breaking

#4400 Adds ConnectionInfo and SecureSession to Ember
  blaze-server/src/main/scala/org/http4s/server/blaze/BlazeServerBuilder.scala
  blaze-server/src/main/scala/org/http4s/server/blaze/SSLContextFactory.scala
  build.sbt
  core/src/main/scala/org/http4s/internal/tls.scala
  ember-server/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala
Labels: enhancement

#4491 cleanup scalafix build
  .github/workflows/ci.yml
  build.sbt
  project/Http4sPlugin.scala
  project/plugins.sbt
  scalafix/build.sbt
  scalafix/project/build.properties
  scalafix/project/plugins.sbt
Labels: RFC
