Repository http4s/http4s, pull requests merged in 2022-01, with the labels that each got.

#5803 Update cats-effect, cats-effect-laws, ... to 3.3.3 in series/0.23
  project/Http4sPlugin.scala
Labels: dependencies, series/0.23

#5810 Replace deprecated object in the imports
  prometheus-metrics/src/main/scala/org/http4s/metrics/prometheus/PrometheusExportService.scala
Labels: series/0.22

#5815 Update jawn-parser to 1.3.2 in series/0.22
  project/Http4sPlugin.scala
Labels: dependencies, series/0.22

#5458 Update Prometheus simpleclient to 0.12.0
  .scala-steward.conf
  project/Http4sPlugin.scala
Labels: module:prometheus-metrics

#5771 Promote http4s.js a bit
  project/SiteConfig.scala
  website/src/hugo/content/default.template.html
  website/src/hugo/content/versions.md
  website/src/hugo/static/templates/no-page-nav.template.html
Labels: docs

#5613 Model If-Range header
  core/src/main/scala/org/http4s/EntityTag.scala
  core/src/main/scala/org/http4s/headers/ETag.scala
  core/src/main/scala/org/http4s/headers/If-Range.scala
  laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
  tests/src/test/scala/org/http4s/headers/IfRangeSuite.scala
Labels: enhancement, module:core, series/0.22

#5817 Update simpleclient, simpleclient_common, ... to 0.14.1
  project/Http4sPlugin.scala
Labels: dependencies

#5820 Update jawn-fs2 to 1.2.0 in series/0.22
  project/Http4sPlugin.scala
Labels: dependencies, series/0.22

#5821 Update jawn-fs2 to 2.2.0 in series/0.23
  project/Http4sPlugin.scala
Labels: dependencies, series/0.23

#5496 Disable logging for Ember client internal retry
  client/src/main/scala/org/http4s/client/middleware/Retry.scala
  ember-client/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
Labels: series/0.22

#5786 Make the output of `asCurl` more human-readable
  core/src/main/scala/org/http4s/Message.scala
  core/src/main/scala/org/http4s/internal/CurlConverter.scala
  tests/src/test/scala/org/http4s/MessageSuite.scala
Labels: enhancement, series/0.22

#5793 Path info index fix
  core/src/main/scala/org/http4s/Uri.scala
  servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
  servlet/src/test/scala/org/http4s/servlet/AsyncHttp4sServletSuite.scala
  servlet/src/test/scala/org/http4s/servlet/BlockingHttp4sServletSuite.scala
  servlet/src/test/scala/org/http4s/servlet/RouterInServletSuite.scala
  servlet/src/test/scala/org/http4s/servlet/TestEclipseServer.scala
Labels: bug, module:servlet, module:core, series/0.22

#5794 Law-driven-design of Path#concat and Path#splitAt
  core/src/main/scala/org/http4s/Message.scala
  core/src/main/scala/org/http4s/Uri.scala
  server/src/test/scala/org/http4s/server/middleware/CORSSuite.scala
  tests/src/test/scala/org/http4s/UriSpec.scala
Labels: enhancement, module:core, series/0.22

#5825 Fix FileService Config linking on JS
  server/shared/src/main/scala/org/http4s/server/staticcontent/FileService.scala
Labels: module:server, series/0.23

#5828 Set 2022 in the `README`
  README.md
Labels: docs

#5829 Fix links to the license on the site
  docs/src/main/mdoc/default.template.html
  website/src/hugo/content/default.template.html
  website/src/hugo/static/templates/no-page-nav.template.html
Labels: docs, series/0.22

#5827 Update jnr-unixsocket to 0.38.17 in series/0.23
  project/Http4sPlugin.scala
Labels: dependencies, series/0.23

#5824 Merge branch 'series/0.21' into series/0.22
  build.sbt
  website/src/hugo/content/contributing.md
Labels: series/0.22

#5789 Refactor some `Http1Connection` methods
  blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
Labels: enhancement, series/0.22

#5784 Update scalafmt-core to 3.2.2 in series/0.22
  .scalafmt.conf
  blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
  blaze-server/src/main/scala/org/http4s/blaze/server/Http1ServerStage.scala
  testing/src/test/scala/org/http4s/testing/AutoCloseableResource.scala
Labels: dependencies, series/0.22

#5834 Update scalafmt-core to 3.3.1 in series/0.22
  .scalafmt.conf
  blaze-core/src/main/scala/org/http4s/blazecore/websocket/Serializer.scala
  blaze-server/src/main/scala/org/http4s/blaze/server/Http1ServerStage.scala
  client/src/main/scala/org/http4s/client/middleware/CookieJar.scala
  core/src/main/scala/org/http4s/MediaType.scala
  core/src/main/scala/org/http4s/websocket/WebSocketFrame.scala
  server/src/main/scala/org/http4s/server/middleware/CORS.scala
  tests/src/test/scala/org/http4s/ContextRequestSuite.scala
Labels: dependencies, series/0.22

#5833 Merge `series/0.22` into `series/0.23`
  blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/ClientTimeoutSuite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/MockClientBuilder.scala
  client/shared/src/main/scala/org/http4s/client/middleware/Retry.scala
  core/shared/src/main/scala/org/http4s/EntityTag.scala
  core/shared/src/main/scala/org/http4s/Message.scala
  core/shared/src/main/scala/org/http4s/Uri.scala
  core/shared/src/main/scala/org/http4s/headers/ETag.scala
  core/shared/src/main/scala/org/http4s/headers/If-Range.scala
  core/shared/src/main/scala/org/http4s/internal/CurlConverter.scala
  docs/src/main/mdoc/default.template.html
  ember-client/shared/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
  laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
  project/Http4sPlugin.scala
  project/build.properties
  project/plugins.sbt
  server/shared/src/test/scala/org/http4s/server/middleware/CORSSuite.scala
  servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
  servlet/src/test/scala/org/http4s/servlet/AsyncHttp4sServletSuite.scala
  servlet/src/test/scala/org/http4s/servlet/BlockingHttp4sServletSuite.scala
  servlet/src/test/scala/org/http4s/servlet/RouterInServletSuite.scala
  servlet/src/test/scala/org/http4s/servlet/TestEclipseServer.scala
  tests/shared/src/test/scala/org/http4s/MessageSuite.scala
  tests/shared/src/test/scala/org/http4s/UriSpec.scala
  tests/shared/src/test/scala/org/http4s/headers/IfRangeSuite.scala
  website/src/hugo/content/default.template.html
  website/src/hugo/static/templates/no-page-nav.template.html
Labels: retarget, series/0.23

#5839 Merge `series/0.23` into `main`
  blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/ClientTimeoutSuite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/MockClientBuilder.scala
  client/shared/src/main/scala/org/http4s/client/middleware/Retry.scala
  core/shared/src/main/scala/org/http4s/EntityTag.scala
  core/shared/src/main/scala/org/http4s/Message.scala
  core/shared/src/main/scala/org/http4s/Uri.scala
  core/shared/src/main/scala/org/http4s/headers/ETag.scala
  core/shared/src/main/scala/org/http4s/headers/If-Range.scala
  core/shared/src/main/scala/org/http4s/internal/CurlConverter.scala
  docs/src/main/mdoc/default.template.html
  ember-client/shared/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
  laws/src/main/scala/org/http4s/laws/discipline/arbitrary.scala
  project/Http4sPlugin.scala
  project/build.properties
  project/plugins.sbt
  server/shared/src/test/scala/org/http4s/server/middleware/CORSSuite.scala
  servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
  servlet/src/test/scala/org/http4s/servlet/AsyncHttp4sServletSuite.scala
  servlet/src/test/scala/org/http4s/servlet/BlockingHttp4sServletSuite.scala
  servlet/src/test/scala/org/http4s/servlet/RouterInServletSuite.scala
  servlet/src/test/scala/org/http4s/servlet/TestEclipseServer.scala
  tests/shared/src/test/scala/org/http4s/MessageSuite.scala
  tests/shared/src/test/scala/org/http4s/UriSpec.scala
  tests/shared/src/test/scala/org/http4s/headers/IfRangeSuite.scala
  website/src/hugo/content/default.template.html
  website/src/hugo/static/templates/no-page-nav.template.html
Labels: retarget

#5840 Re-enable broken ember client test
  ember-client/shared/src/test/scala/org/http4s/ember/client/EmberClientSuite.scala
Labels: series/0.23

#5842 Fix the `lint` command
  build.sbt
Labels: series/0.22

#5843 Enable fatal warnings in `lint`/`quicklint` commands
  build.sbt
Labels: series/0.23

#5838 Update cats-effect, cats-effect-laws, ... to 3.3.4 in series/0.23
  project/Http4sPlugin.scala
Labels: dependencies, series/0.23

#5837 FileService Server Middleware: readability
  server/shared/src/main/scala/org/http4s/server/staticcontent/FileService.scala
Labels: series/0.23

#5846 Update dev shell
  .envrc
  flake.lock
  flake.nix
  nix/hugo-deps.nix
  nix/hugo.nix
  nix/nixpkgs-version.json
  nix/pkgs.nix
  shell.nix
Labels: series/0.22

#5847 Merge from v0.22
  .envrc
  .scalafmt.conf
  blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
  blaze-core/src/main/scala/org/http4s/blazecore/websocket/Serializer.scala
  blaze-server/src/main/scala/org/http4s/blaze/server/Http1ServerStage.scala
  client/shared/src/main/scala/org/http4s/client/middleware/CookieJar.scala
  core/shared/src/main/scala/org/http4s/MediaType.scala
  core/shared/src/main/scala/org/http4s/websocket/WebSocketFrame.scala
  flake.lock
  flake.nix
  nix/hugo-deps.nix
  nix/hugo.nix
  nix/nixpkgs-version.json
  nix/pkgs.nix
  server/shared/src/main/scala/org/http4s/server/middleware/CORS.scala
  server/shared/src/main/scala/org/http4s/server/middleware/HttpMethodOverrider.scala
  server/shared/src/main/scala/org/http4s/server/staticcontent/FileService.scala
  shell.nix
  testing/shared/src/test/scala/org/http4s/testing/AutoCloseableResource.scala
  tests/shared/src/test/scala/org/http4s/ContextRequestSuite.scala
Labels: series/0.23

#5853 Update locales-minimal-en_us-db to 1.3.0 in series/0.23
  project/Http4sPlugin.scala
Labels: dependencies, series/0.23

#5855 Fix description for pinned CE2 dependencies
  .scala-steward.conf
Labels: CI, dependencies, series/0.22

#5856 Steward exclusions in 0.23 for dependencies merged forward from 0.22
  .scala-steward.conf
Labels: CI, dependencies, series/0.23

#5857 Update netty-buffer, netty-codec-http to 4.1.73.Final in series/0.22
  project/Http4sPlugin.scala
Labels: dependencies, series/0.22

#5851 Update sbt-scalafix to 0.9.34 in series/0.22
  .github/workflows/ci.yml
  project/Http4sPlugin.scala
  project/plugins.sbt
  scalafix/project/plugins.sbt
Labels: dependencies, series/0.22

#5860 Merge series/0.22 into series/0.23
  .github/workflows/ci.yml
  project/Http4sPlugin.scala
  project/plugins.sbt
  scalafix/project/plugins.sbt
Labels: series/0.23

#5863 Upgrade typelevel-nix to pick up Metals
  flake.lock
Labels: series/0.22

#5848 Auto-select available port for ember suites
  ember-server/jvm/src/test/scala/org/http4s/ember/server/EmberServerMtlsSuite.scala
  ember-server/jvm/src/test/scala/org/http4s/ember/server/EmberServerWebSocketSuite.scala
  ember-server/shared/src/test/scala/org/http4s/ember/server/ConnectionSuite.scala
  ember-server/shared/src/test/scala/org/http4s/ember/server/EmberServerSuite.scala
Labels: testing, module:ember-server, series/0.23

#5869 Update slf4j-api to 1.7.33 in series/0.22
  project/Http4sPlugin.scala
Labels: dependencies, series/0.22

#5873 Update blaze-http to 0.15.3 in series/0.22
  project/Http4sPlugin.scala
Labels: dependencies, series/0.22

#5864 Fix customDnsResolver in BlazeClientBuilder
  blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClientBuilder.scala
Labels: bug, module:blaze-client, series/0.22

#5876 Fix some links in the scaladoc
  core/src/main/scala/org/http4s/MediaType.scala
  core/src/main/scala/org/http4s/Message.scala
  core/src/main/scala/org/http4s/Uri.scala
  core/src/main/scala/org/http4s/internal/package.scala
  jetty-server/src/main/scala/org/http4s/jetty/server/JettyBuilder.scala
  jetty-server/src/main/scala/org/http4s/jetty/server/JettyThreadPools.scala
  server/src/main/scala/org/http4s/server/middleware/BracketRequestResponse.scala
  server/src/main/scala/org/http4s/server/middleware/CORS.scala
  server/src/main/scala/org/http4s/server/middleware/ConcurrentRequests.scala
Labels: docs, series/0.22

#5880 Update log4cats-slf4j, log4cats-testing to 1.5.1 in series/0.22
  project/Http4sPlugin.scala
Labels: dependencies, series/0.22

#5884 Refactor some `Resource` usage
  blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClient.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
  client/jvm/src/main/scala/org/http4s/client/JavaNetClientBuilder.scala
  client/shared/src/main/scala/org/http4s/client/Client.scala
  client/shared/src/main/scala/org/http4s/client/middleware/Metrics.scala
  ember-server/shared/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala
Labels: series/0.23

#5885 Remove mentioning of `ContextShift` in the AHC scaladoc
  async-http-client/src/main/scala/org/http4s/asynchttpclient/AsyncHttpClient.scala
Labels: docs, series/0.23

#5886 Use blocking thread pool on joining Jetty's thread pool
  jetty-server/src/main/scala/org/http4s/jetty/server/JettyThreadPools.scala
Labels: enhancement, series/0.23

#5875 Deprecate the `BracketRequestResponse#exitCaseToOutcome`
  server/shared/src/main/scala/org/http4s/server/middleware/BracketRequestResponse.scala
Labels: series/0.23

#5887 Use blocking thread pool in the Prometheus metrics
  prometheus-metrics/src/main/scala/org/http4s/metrics/prometheus/Prometheus.scala
Labels: enhancement, module:prometheus-metrics, series/0.23

#5881 Support parsing response bodies without Content-Length in ember
  ember-core/src/main/scala/org/http4s/ember/core/Parser.scala
  ember-core/src/test/scala/org/http4s/ember/core/ParserSuite.scala
Labels: series/0.23

#5896 Use `port` syntax
  ember-server/jvm/src/test/scala/org/http4s/ember/server/EmberServerMtlsSuite.scala
  ember-server/jvm/src/test/scala/org/http4s/ember/server/EmberServerWebSocketSuite.scala
  ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala
  ember-server/shared/src/test/scala/org/http4s/ember/server/ConnectionSuite.scala
  ember-server/shared/src/test/scala/org/http4s/ember/server/EmberServerSuite.scala
  server/shared/src/test/scala/org/http4s/server/middleware/ErrorActionSuite.scala
Labels: series/0.23

#5901 Use loopback address for Netty scaffold
  client/src/test/scala/org/http4s/client/scaffold/NettyTestServer.scala
Labels: series/0.22

#5900 Update to sbt-http4s-org 0.10.0
  .github/workflows/ci.yml
  build.sbt
  project/Http4sPlugin.scala
  project/plugins.sbt
Labels: series/0.22

#5903 Update scalatags to 0.11.1
  project/Http4sPlugin.scala
Labels: dependencies

#5897 Use blocking thread pool in the `JettyClient#resource`
  jetty-client/src/main/scala/org/http4s/jetty/client/JettyClient.scala
Labels: series/0.23

#5910 Update scalafmt-core to 3.3.2 in series/0.22
  .scalafmt.conf
Labels: dependencies, series/0.22

#5907 Add EntityEncoder[F, ByteVector]
  core/src/main/scala/org/http4s/EntityDecoder.scala
  core/src/main/scala/org/http4s/EntityEncoder.scala
Labels: series/0.22

#5908 Enable snapshots for 0.22
  .github/workflows/ci.yml
  build.sbt
Labels: series/0.22

#5861 Stale connection mitigation in blaze-client
  blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClient.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClientBuilder.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientBase.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientSuite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/ClientTimeoutSuite.scala
Labels: enhancement, module:blaze-client, series/0.22

#5915 Update tomcat-catalina, tomcat-coyote, ... to 9.0.58 in series/0.22
  project/Http4sPlugin.scala
Labels: dependencies, series/0.22

#5920 Revert "Enable snapshots for 0.22" (#5908)
  .github/workflows/ci.yml
  build.sbt
Labels: series/0.22

#5918 Add `scalafixInternalRules` to root project
  build.sbt
Labels: series/0.22

#5922 Update sbt-http4s-org to 0.10.1 in series/0.22
  project/plugins.sbt
Labels: dependencies, series/0.22

#5899 maxIdleDuration on blaze connections
  blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClient.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClientBuilder.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/ConnectionManager.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/Http1Client.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/PoolManager.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/PoolManagerSuite.scala
Labels: enhancement, module:blaze-client, series/0.22

#5925 Merge `series/0.23` into `main`
  .scala-steward.conf
  ember-core/src/main/scala/org/http4s/ember/core/Parser.scala
  ember-core/src/test/scala/org/http4s/ember/core/ParserSuite.scala
  ember-server/jvm/src/test/scala/org/http4s/ember/server/EmberServerMtlsSuite.scala
  ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala
  ember-server/shared/src/test/scala/org/http4s/ember/server/ConnectionSuite.scala
  ember-server/shared/src/test/scala/org/http4s/ember/server/EmberServerSuite.scala
  jetty-client/src/main/scala/org/http4s/jetty/client/JettyClient.scala
  project/Http4sPlugin.scala
  server/shared/src/test/scala/org/http4s/server/middleware/ErrorActionSuite.scala
Labels: retarget

#5928 Non-deadlocking RouterInServletSuite
  servlet/src/test/scala/org/http4s/servlet/BlockingHttp4sServletSuite.scala
  servlet/src/test/scala/org/http4s/servlet/RouterInServletSuite.scala
Labels: series/0.23

#5931 Update scalafmt-core to 3.3.3 in series/0.22
  .scalafmt.conf
Labels: dependencies, series/0.22

#5933 Merge scalafmt-core forward from 0.22
  .scala-steward.conf
Labels: series/0.23

#5926 Merge 0.22 -> 0.23
  .github/workflows/ci.yml
  .scalafmt.conf
  blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClient.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClientBuilder.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/ConnectionManager.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/PoolManager.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientBase.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientSuite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/ClientTimeoutSuite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/PoolManagerSuite.scala
  build.sbt
  client/jvm/src/test/scala/org/http4s/client/scaffold/NettyTestServer.scala
  core/shared/src/main/scala/org/http4s/EntityDecoder.scala
  core/shared/src/main/scala/org/http4s/EntityEncoder.scala
  project/Http4sPlugin.scala
  project/plugins.sbt
  server/shared/src/main/scala-2/org/http4s/server/staticcontent/FileServiceConfigCompat.scala
  server/shared/src/main/scala-3/org/http4s/server/staticcontent/FileServiceConfigCompat.scala
  server/shared/src/main/scala/org/http4s/server/staticcontent/FileService.scala
Labels: series/0.23

#5935 Update sbt-http4s-org to 0.11.0 in series/0.22
  project/plugins.sbt
Labels: dependencies, series/0.22

#5937 remove empty excludes from release notes config
  .github/release.yml
Labels: series/0.22

#5939 Push behind-the-scenes label down the changelog
  .github/release.yml
Labels: series/0.22

#5941 Add module labeling to mergify config
  .mergify.yml
Labels: behind-the-scenes

#5940 Merge from 0.22
  .github/release.yml
  .scalafmt.conf
  website/src/hugo/content/changelog.md
Labels: series/0.23

#5943 Delete zombie specs2 code
  licenses/LICENSE_scalaz-specs2
  licenses/LICENSE_specs2
  specs2/src/test/scala/org/http4s/Http4sSpec.scala
Labels: series/0.23, behind-the-scenes

#5944 Replace our TestExecutionContext
  blaze-client/src/test/scala/org/http4s/blaze/client/ClientTimeoutSuite.scala
  blaze-server/src/test/scala/org/http4s/blaze/server/Http1ServerStageSpec.scala
  testing/js/src/test/scala/org/http4s/Http4sSuitePlatform.scala
  testing/jvm/src/test/scala/org/http4s/Http4sSuitePlatform.scala
  testing/shared/src/test/scala/org/http4s/Http4sSuite.scala
Labels: module:blaze-client, module:blaze-server, series/0.23, behind-the-scenes

#5942 Release v0.23.8
  website/src/hugo/content/changelog.md
Labels: series/0.23

#5949 Ignore slf4j-api
  .scala-steward.conf
Labels: series/0.23, behind-the-scenes

#5945 Remove janky thread pool from BlazeHttp1ClientSuite
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeHttp1ClientSuite.scala
Labels: module:blaze-client, series/0.23, behind-the-scenes

#5950 Add withMaxIdleDuration setter to BlazeClientBuilder
  blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClientBuilder.scala
Labels: module:blaze-client, series/0.22

#5952 Update http4s-circe, http4s-ember-client to 0.23.8 in series/0.22
  project/build.sbt
Labels: dependencies, series/0.22

#5947 Update slf4j-api to 1.7.35 in series/0.22
  project/Http4sPlugin.scala
Labels: dependencies, series/0.22

#5934 Merge 0.23 into main
  .github/release.yml
  .github/workflows/ci.yml
  .scala-steward.conf
  .scalafmt.conf
  blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClient.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClientBuilder.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/ConnectionManager.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/PoolManager.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientBase.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientSuite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/ClientTimeoutSuite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/PoolManagerSuite.scala
  blaze-server/src/test/scala/org/http4s/blaze/server/Http1ServerStageSpec.scala
  build.sbt
  client/jvm/src/test/scala/org/http4s/client/scaffold/NettyTestServer.scala
  core/shared/src/main/scala/org/http4s/EntityDecoder.scala
  core/shared/src/main/scala/org/http4s/EntityEncoder.scala
  licenses/LICENSE_scalaz-specs2
  licenses/LICENSE_specs2
  project/Http4sPlugin.scala
  project/plugins.sbt
  servlet/src/test/scala/org/http4s/servlet/BlockingHttp4sServletSuite.scala
  servlet/src/test/scala/org/http4s/servlet/RouterInServletSuite.scala
  specs2/src/test/scala/org/http4s/Http4sSpec.scala
  testing/js/src/test/scala/org/http4s/Http4sSuitePlatform.scala
  testing/jvm/src/test/scala/org/http4s/Http4sSuitePlatform.scala
  testing/shared/src/test/scala/org/http4s/Http4sSuite.scala
  website/src/hugo/content/changelog.md
Labels: module:servlet, module:core, module:blaze-client, module:client, module:blaze-server, behind-the-scenes

#5657 Ember H2 support
  .github/workflows/ci.yml
  build.sbt
  core/shared/src/main/scala/org/http4s/Message.scala
  ember-client/js/yarn.lock
  ember-client/shared/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
  ember-core/js/src/main/scala/org/http4s/ember/core/h2/H2TLSPlatform.scala
  ember-core/js/src/main/scala/org/http4s/ember/core/h2/HpackPlatform.scala
  ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/Compressor.scala
  ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/Decompressor.scala
  ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/Header.scala
  ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/HpackOptions.scala
  ember-core/js/yarn.lock
  ember-core/jvm/src/main/scala/org/http4s/ember/core/h2/H2TLSPlatform.scala
  ember-core/jvm/src/main/scala/org/http4s/ember/core/h2/HpackPlatform.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/ChunkedEncoding.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/EmberException.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/Encoder.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/Parser.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/Shared.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/Util.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Connection.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Error.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Frame.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Keys.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Server.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Stream.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2TLS.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/Hpack.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/Preface.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/PseudoHeaders.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/package.scala
  ember-core/shared/src/test/scala/org/http4s/ember/core/EncoderSuite.scala
  ember-core/shared/src/test/scala/org/http4s/ember/core/ParserSuite.scala
  ember-core/shared/src/test/scala/org/http4s/ember/core/RequestSplittingSuite.scala
  ember-core/shared/src/test/scala/org/http4s/ember/core/ResponseSplittingSuite.scala
  ember-core/shared/src/test/scala/org/http4s/ember/core/StreamingParserSuite.scala
  ember-core/shared/src/test/scala/org/http4s/ember/core/TraversalSpec.scala
  ember-core/shared/src/test/scala/org/http4s/ember/core/UtilSuite.scala
  ember-core/shared/src/test/scala/org/http4s/ember/core/h2/FrameSpec.scala
  ember-core/shared/src/test/scala/org/http4s/ember/core/h2/HpackSuite.scala
  ember-server/js/yarn.lock
  ember-server/shared/src/main/scala/org/http4s/ember/server/EmberServerBuilder.scala
  ember-server/shared/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala
  examples/ember-client-h2/src/main/scala/com/example/http4s/ember/EmberClientH2Example.scala
  examples/ember-client-h2/yarn.lock
  examples/ember-server-h2/src/main/scala/com/example/http4s/ember/EmberServerH2Example.scala
  examples/ember-server-h2/yarn.lock
  examples/ember/src/main/resources/logback.xml
  examples/ember/src/main/scala/com/example/http4s/ember/EmberClientH2Example.scala
  examples/ember/src/main/scala/com/example/http4s/ember/EmberServerH2Example.scala
  project/plugins.sbt
  tests/shared/src/test/scala/org/http4s/MessageSuite.scala
Labels: module:core, module:ember-client, module:ember-server, module:ember-core, series/0.23

#5955 Clean up Throwables in HTTP/2
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Connection.scala
Labels: module:ember-core, series/0.23, behind-the-scenes

#5954 Fix HTTP/2 warnings and restore compiler settings
  build.sbt
  ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/Compressor.scala
  ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/Decompressor.scala
  ember-core/jvm/src/main/scala/org/http4s/ember/core/h2/H2TLSPlatform.scala
  ember-core/jvm/src/main/scala/org/http4s/ember/core/h2/HpackPlatform.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Client.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Connection.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Frame.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Server.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/H2Stream.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/PseudoHeaders.scala
Labels: module:ember-core, series/0.23, behind-the-scenes

#5958 Get http4s upgrades for build from 0.22
  .scala-steward.conf
Labels: series/0.23, behind-the-scenes

#5963 Remove mdoc/laika sbt plugins
  project/plugins.sbt
Labels: series/0.22

#5385 Resourcify blaze client
  blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClient.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/BlazeConnection.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/Connection.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/PoolManager.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientConnectionReuseSuite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientSuite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/ClientTimeoutSuite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/Http1ClientStageSuite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/PoolManagerSuite.scala
  blaze-core/src/main/scala/org/http4s/blazecore/util/EntityBodyWriter.scala
  blaze-core/src/main/scala/org/http4s/blazecore/util/package.scala
  build.sbt
  client/src/test/scala/org/http4s/client/scaffold/HandlersToNettyAdapter.scala
Labels: module:blaze-client, module:client, module:blaze-core, series/0.22

#5520 Create WebSocket client API
  client/src/main/scala/org/http4s/client/websocket/WSClient.scala
Labels: module:client, series/0.22

#5965 Privatize web socket client pending concrete implementation
  client/src/main/scala/org/http4s/client/websocket/WSClient.scala
Labels: module:client, series/0.22, behind-the-scenes

#5964 Release v0.22.10
  website/src/hugo/content/changelog.md
Labels: series/0.22

#5957 Merge from 0.22
  blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClient.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/BlazeClientBuilder.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/BlazeConnection.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/Connection.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/Http1Connection.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/PoolManager.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientConnectionReuseSuite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/BlazeClientSuite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/ClientTimeoutSuite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/Http1ClientStageSuite.scala
  blaze-client/src/test/scala/org/http4s/blaze/client/PoolManagerSuite.scala
  blaze-core/src/main/scala/org/http4s/blazecore/util/EntityBodyWriter.scala
  blaze-core/src/main/scala/org/http4s/blazecore/util/package.scala
  build.sbt
  client/jvm/src/test/scala/org/http4s/client/scaffold/HandlersToNettyAdapter.scala
  client/shared/src/main/scala/org/http4s/client/websocket/WSClient.scala
  project/Http4sPlugin.scala
  project/build.sbt
  project/plugins.sbt
  website/src/hugo/content/changelog.md
Labels: module:blaze-client, module:client, module:blaze-core, series/0.23, behind-the-scenes

#5967 Update cats-effect, cats-effect-laws, ... to 3.3.5 in series/0.23
  project/Http4sPlugin.scala
Labels: dependencies, series/0.23

#5966 Release v0.23.9
  website/src/hugo/content/changelog.md
Labels: series/0.23, behind-the-scenes

#5969 Update scalafmt-core to 3.4.0 in series/0.22
  .scalafmt.conf
Labels: dependencies, series/0.22

#5970 Use ember in docs
  build.sbt
  docs/src/main/mdoc/README.md
  docs/src/main/mdoc/client.md
  docs/src/main/mdoc/json.md
  docs/src/main/mdoc/service.md
  docs/src/main/mdoc/static.md
  docs/src/main/mdoc/streaming.md
  docs/src/main/resources/logback.xml
Labels: docs, series/0.23

#5972 Update http4s-circe, http4s-ember-client to 0.23.9 in series/0.22
  project/build.sbt
Labels: dependencies, series/0.22

#5968 Update sbt-http4s-org to 0.11.1 in series/0.22
  .github/workflows/ci.yml
  project/plugins.sbt
Labels: dependencies, series/0.22

#5973 Update static content docs, fix deprecations
  docs/src/main/mdoc/static.md
Labels: docs, series/0.23
