Repository http4s/http4s, pull requests merged in 2022-02, with the labels that each got.

#5976 Update sbt to 1.6.2 in series/0.22
  project/build.properties
Labels: dependencies, series/0.22

#5984 Tweak json.md to work on scala 2.13
  docs/src/main/mdoc/json.md
Labels: docs, series/0.23

#5985 Update scala3-library, ... to 3.1.1 in series/0.23
  .github/workflows/ci.yml
  project/Http4sPlugin.scala
Labels: dependencies, series/0.23

#5979 Mdoc warnings v23
  docs/src/main/mdoc/dsl.md
  docs/src/main/mdoc/streaming.md
Labels: docs, series/0.23

#5991 Fix regression in routing dsl
  dsl/src/main/scala/org/http4s/dsl/impl/Path.scala
  server/src/test/scala/org/http4s/server/RouterSuite.scala
Labels: module:server, module:dsl, series/0.22

#5987 Merge 0.22 to 0.23
  .github/workflows/ci.yml
  .scalafmt.conf
  project/build.properties
  project/build.sbt
  project/plugins.sbt
Labels: series/0.23, behind-the-scenes

#5993 Update metrics-core, metrics-json to 4.2.8 in series/0.22
  project/Http4sPlugin.scala
Labels: module:dropwizard-metrics, dependencies, series/0.22

#5975 Improve `WSClient` API
  build.sbt
  client/src/main/scala/org/http4s/client/websocket/WSClient.scala
Labels: module:client, series/0.22

#5994 Respect URI locality in UrlFormLifter
  server/src/main/scala/org/http4s/server/middleware/UrlFormLifter.scala
  server/src/test/scala/org/http4s/server/middleware/UrlFormLifterSuite.scala
Labels: module:server, series/0.22

#5996 Release v0.22.11
  website/src/hugo/content/changelog.md
Labels: docs, series/0.22

#5995 Merge from 0.22
  dsl/src/main/scala/org/http4s/dsl/impl/Path.scala
  project/Http4sPlugin.scala
  server/shared/src/main/scala/org/http4s/server/middleware/UrlFormLifter.scala
  server/shared/src/test/scala/org/http4s/server/RouterSuite.scala
  server/shared/src/test/scala/org/http4s/server/middleware/UrlFormLifterSuite.scala
  website/src/hugo/content/changelog.md
Labels: module:server, module:dsl, series/0.23, behind-the-scenes

#5977 Remove most mdoc nest modifiers
  docs/src/main/mdoc/auth.md
  docs/src/main/mdoc/cors.md
  docs/src/main/mdoc/csrf.md
  docs/src/main/mdoc/dsl.md
  docs/src/main/mdoc/entity.md
  docs/src/main/mdoc/gzip.md
  docs/src/main/mdoc/hsts.md
  docs/src/main/mdoc/json.md
  docs/src/main/mdoc/middleware.md
  docs/src/main/mdoc/service.md
  docs/src/main/mdoc/static.md
  docs/src/main/mdoc/testing.md
Labels: docs, series/0.23

#5998 Release v0.23.10
  website/src/hugo/content/changelog.md
Labels: docs, series/0.23

#5337 Drop Scala 2.12 from 1.0
  .github/workflows/ci.yml
  async-http-client/src/main/scala/org/http4s/asynchttpclient/AsyncHttpClient.scala
  async-http-client/src/main/scala/org/http4s/asynchttpclient/AsyncHttpClientStats.scala
  bench/src/main/scala/org/http4s/bench/NioCharsetBench.scala
  bench/src/main/scala/org/http4s/bench/QueryParamBench.scala
  blaze-client/src/main/scala/org/http4s/blaze/client/PoolManager.scala
  build.sbt
  client/jvm/src/main/scala/org/http4s/client/JavaNetClientBuilder.scala
  core/jvm/src/main/scala/org/http4s/CharsetPlatform.scala
  core/shared/src/main/scala-2.12/org/http4s/internal/CollectionCompat.scala
  core/shared/src/main/scala-2.13/org/http4s/LiteralSyntaxMacros.scala
  core/shared/src/main/scala-2.13/org/http4s/MediaTypePlaform.scala
  core/shared/src/main/scala-2.13/org/http4s/QValuePlatform.scala
  core/shared/src/main/scala-2.13/org/http4s/UriPlatform.scala
  core/shared/src/main/scala-2.13/org/http4s/internal/CollectionCompat.scala
  core/shared/src/main/scala-2.13/org/http4s/syntax/LiteralsSyntax.scala
  core/shared/src/main/scala/org/http4s/Charset.scala
  core/shared/src/main/scala/org/http4s/Query.scala
  core/shared/src/main/scala/org/http4s/UrlForm.scala
  core/shared/src/main/scala/org/http4s/multipart/Boundary.scala
  jetty-client/src/main/scala/org/http4s/jetty/client/ResponseListener.scala
  okhttp-client/src/main/scala/org/http4s/okhttp/client/OkHttpBuilder.scala
  project/Http4sPlugin.scala
  server/shared/src/main/scala/org/http4s/server/staticcontent/WebjarService.scala
  servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
  tests/shared/src/test/scala/org/http4s/UrlFormSpec.scala
  tests/shared/src/test/scala/org/http4s/parser/QueryParserSpec.scala
  tomcat-server/src/main/scala/org/http4s/tomcat/server/TomcatBuilder.scala
Labels: docs, module:servlet, module:core, module:blaze-client, module:client, module:server, module:async-http-client, module:okhttp-client, module:jetty-client

#6002 Update http4s-circe, http4s-ember-client to 0.23.10 in series/0.22
  project/build.sbt
Labels: dependencies, series/0.22

#6003 Release v1.0.0-M31
  website/src/hugo/content/changelog.md
Labels: docs

#6001 Add convenience methods to `WSConnectionHighLevel`
  client/src/main/scala/org/http4s/client/websocket/WSClient.scala
Labels: module:client, series/0.22, behind-the-scenes

#5999 Add scaladocs for EmberClientBuilder
  ember-client/shared/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
Labels: module:ember-client, series/0.23

#6005 Make `WSClient` and friends public
  build.sbt
  client/shared/src/main/scala/org/http4s/client/websocket/WSClient.scala
Labels: module:client, series/0.23

#6006 Update scalafmt-core to 3.4.1 in series/0.22
  .scalafmt.conf
  blaze-server/src/test/scala/org/http4s/blaze/server/Http1ServerStageSpec.scala
  circe/src/main/scala/org/http4s/circe/middleware/JsonDebugErrorHandler.scala
  core/src/main/scala/org/http4s/RequestPrelude.scala
  server/src/main/scala/org/http4s/server/middleware/ErrorAction.scala
  server/src/main/scala/org/http4s/server/package.scala
Labels: module:core, module:server, module:blaze-server, module:circe, dependencies, series/0.22

#6007 Update simpleclient, simpleclient_common, ... to 0.15.0
  project/Http4sPlugin.scala
Labels: dependencies

#6008 Fresh up the version page
  website/src/hugo/content/versions.md
Labels: docs

#6010 Update scalafmt-core to 3.4.2 in series/0.22
  .scalafmt.conf
Labels: dependencies, series/0.22

#6020 Merge Jetty forward from 0.22
  .scala-steward.conf
Labels: series/0.23, behind-the-scenes

#6022 Ignore Jetty HTTP/2 updates
  .scala-steward.conf
Labels: series/0.22

#6027 Flush the prelude in non-blocking Servlet IO
  servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
  servlet/src/main/scala/org/http4s/servlet/ServletIo.scala
Labels: module:servlet, series/0.21

#6030 Update slf4j-api to 1.7.36 in series/0.22
  project/Http4sPlugin.scala
Labels: dependencies, series/0.22

#6004 Merge 0.22 into 0.23
  client/shared/src/main/scala/org/http4s/client/websocket/WSClient.scala
  project/build.sbt
Labels: module:client, series/0.23, behind-the-scenes

#6031 Merge 0.22 -> 0.23
  .scalafmt.conf
  blaze-server/src/test/scala/org/http4s/blaze/server/Http1ServerStageSpec.scala
  circe/src/main/scala/org/http4s/circe/middleware/JsonDebugErrorHandler.scala
  core/shared/src/main/scala/org/http4s/Message.scala
  core/shared/src/main/scala/org/http4s/RequestPrelude.scala
  project/Http4sPlugin.scala
  project/plugins.sbt
  server/shared/src/main/scala/org/http4s/server/middleware/ErrorAction.scala
  server/shared/src/main/scala/org/http4s/server/package.scala
Labels: module:core, module:server, module:blaze-server, module:circe, series/0.23, behind-the-scenes

#6028 Render continually between response prelude and body
  blaze-server/src/main/scala/org/http4s/server/blaze/Http1ServerStage.scala
  blaze-server/src/main/scala/org/http4s/server/blaze/Http2NodeStage.scala
  ember-server/src/main/scala/org/http4s/ember/server/internal/ServerHelpers.scala
  servlet/src/main/scala/org/http4s/servlet/AsyncHttp4sServlet.scala
  servlet/src/main/scala/org/http4s/servlet/Http4sServlet.scala
Labels: module:servlet, module:ember-server, module:blaze-server, series/0.21

#6033 Release v0.21.32
  build.sbt
  project/plugins.sbt
  website/src/hugo/content/changelog.md
Labels: docs, behind-the-scenes, series/0.21

#6034 Build tweaks in case there's another 0.21
  build.sbt
  project/plugins.sbt
Labels: CI, behind-the-scenes

#6038 Update scalafmt-core to 3.4.3 in series/0.22
  .scalafmt.conf
Labels: dependencies, series/0.22

#6045 Update sbt-scalajs, scalajs-compiler, ... to 1.9.0 in series/0.23
  project/plugins.sbt
Labels: dependencies, series/0.23

#6023 Upgrade to jetty-9.4.45.v20220203 on series/0.22
  jetty-server/src/main/scala/org/http4s/jetty/server/JettyLifeCycle.scala
  project/Http4sPlugin.scala
Labels: module:jetty-server, series/0.22

#6009 Replace npm hpack.js with pure Scala.js hpack
  build.sbt
  ember-client/js/yarn.lock
  ember-core/js/src/main/scala/org/http4s/ember/core/h2/HpackPlatform.scala
  ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/Compressor.scala
  ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/Decompressor.scala
  ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/Header.scala
  ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/HpackOptions.scala
  ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/package.scala
  ember-core/js/yarn.lock
  ember-core/jvm/src/main/scala/org/http4s/ember/core/h2/HpackPlatform.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/Hpack.scala
  ember-server/js/yarn.lock
  examples/ember-client-h2/yarn.lock
  examples/ember-server-h2/yarn.lock
  project/Http4sPlugin.scala
  project/plugins.sbt
Labels: module:ember-client, module:ember-server, module:ember-core, series/0.23

#6052 Update sbt-http4s-org to 0.12.1 in series/0.22
  .github/workflows/ci.yml
  project/plugins.sbt
Labels: dependencies, series/0.22

#6053 Update http4s-crypto to 0.2.2 in series/0.23
  project/Http4sPlugin.scala
Labels: dependencies, series/0.23

#6021 docs: remove workarounds for issues in Laika 0.18.0
  build.sbt
  docs/src/main/mdoc/default.template.html
  project/HeliumExtensions.scala
  project/SiteConfig.scala
  website/src/hugo/content/code-of-conduct.md
  website/src/hugo/content/default.template.html
  website/src/hugo/content/landing.template.html
  website/src/hugo/static/helium/laika-versions.js
  website/src/hugo/static/templates/no-page-nav.template.html
Labels: docs, series/0.22

#6054 Merge 0.22 -> 0.23
  .github/workflows/ci.yml
  .scalafmt.conf
  build.sbt
  docs/src/main/mdoc/default.template.html
  jetty-server/src/main/scala/org/http4s/jetty/server/JettyLifeCycle.scala
  project/HeliumExtensions.scala
  project/Http4sPlugin.scala
  project/SiteConfig.scala
  project/plugins.sbt
  website/src/hugo/content/code-of-conduct.md
  website/src/hugo/content/default.template.html
  website/src/hugo/content/landing.template.html
  website/src/hugo/static/helium/laika-versions.js
  website/src/hugo/static/templates/no-page-nav.template.html
Labels: docs, module:jetty-server, series/0.23, behind-the-scenes

#6065 Update fs2-core, fs2-io, ... to 3.2.5 in series/0.23
  project/Http4sPlugin.scala
Labels: dependencies, series/0.23

#6061 Update sbt-buildinfo to 0.11.0
  project/plugins.sbt
Labels: dependencies

#6073 Update cats-effect, cats-effect-laws, ... to 3.3.6 in series/0.23
  project/Http4sPlugin.scala
Labels: dependencies, series/0.23

#6056 Merge 0.23 -> main
  .github/workflows/ci.yml
  .scala-steward.conf
  .scalafmt.conf
  blaze-server/src/test/scala/org/http4s/blaze/server/Http1ServerStageSpec.scala
  build.sbt
  circe/src/main/scala/org/http4s/circe/middleware/JsonDebugErrorHandler.scala
  client/shared/src/main/scala/org/http4s/client/websocket/WSClient.scala
  core/shared/src/main/scala/org/http4s/Message.scala
  core/shared/src/main/scala/org/http4s/RequestPrelude.scala
  docs/src/main/mdoc/default.template.html
  ember-client/js/yarn.lock
  ember-client/shared/src/main/scala/org/http4s/ember/client/EmberClientBuilder.scala
  ember-core/js/src/main/scala/org/http4s/ember/core/h2/HpackPlatform.scala
  ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/Compressor.scala
  ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/Decompressor.scala
  ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/Header.scala
  ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/HpackOptions.scala
  ember-core/js/src/main/scala/org/http4s/ember/core/h2/facade/package.scala
  ember-core/js/yarn.lock
  ember-core/jvm/src/main/scala/org/http4s/ember/core/h2/HpackPlatform.scala
  ember-core/shared/src/main/scala/org/http4s/ember/core/h2/Hpack.scala
  ember-server/js/src/test/scala/org/http4s/ember/server/EmberServerWebSocketSuitePlatform.scala
  ember-server/js/yarn.lock
  ember-server/jvm/src/test/scala/org/http4s/ember/server/EmberServerWebSocketSuite.scala
  ember-server/jvm/src/test/scala/org/http4s/ember/server/EmberServerWebSocketSuitePlatform.scala
  ember-server/shared/src/test/scala/org/http4s/ember/server/EmberServerWebSocketSuite.scala
  examples/ember-client-h2/yarn.lock
  examples/ember-server-h2/yarn.lock
  jetty-server/src/main/scala/org/http4s/jetty/server/JettyLifeCycle.scala
  project/HeliumExtensions.scala
  project/Http4sPlugin.scala
  project/SiteConfig.scala
  project/build.sbt
  project/plugins.sbt
  server/shared/src/main/scala/org/http4s/server/middleware/ErrorAction.scala
  server/shared/src/main/scala/org/http4s/server/package.scala
  website/src/hugo/content/code-of-conduct.md
  website/src/hugo/content/default.template.html
  website/src/hugo/content/landing.template.html
  website/src/hugo/static/templates/no-page-nav.template.html
Labels: docs, module:core, module:ember-client, module:ember-server, module:client, module:jetty-server, module:server, module:blaze-server, module:ember-core, module:circe, behind-the-scenes
